### ISSUE TITLE
Preprocessing inputs before passing them to prts

### ISSUE THREAD

**Issue by Famondir** [maths/moodle-qtype_stack#763] opened 2021-12-22 12:36 UTC
Hi all,
up to my search in the issue archive my feature request semms to be linked to those of the following two issues:
#681 #740 

What we have:
We have questions for our physics labs that guide students with their evaluation by checking for mistakes (and even aftereffects of earlier mistakes) step by step which results in a lot of prts (e.g. 93 prts). To speed up the calculation the evaluation for significant numbers, correct units and so on realised by subnodes of each tree but in the prt feedback variables area (up to 7300 signs of code).

What is our problem:
We have a bunch of user inputs (up to 40) for their measure results and all calculations are based on their inputs. Unfortunately we can't calculate the correct responses in the question variables area because we don't have the user input now. This way we have to do it in the feedback variables area and repeat this for every prt because we want to check for after effects and so on.

To keep the code synchronised is realy a bother (change it in over 50 prt fields and don't miss one). Also our maxima server is pretty exausted when multiple students run those exercises simultaniousely.

My naive soloution:
Getting a common variable area where you can calculations based on the user inputs that get passed down to all prts. That would reduce the hassle of maintaining copied code a lot.

As far as I understood there might be a problem with missing inputs that would hinder all prts to being evaluated. But I don't realy understand how you get them working seperated right now. Is every prt called with a reference (or even a copy) on each input and the common variables? How would a post input variable area hinder the individual evaluation of a prt?

Sincerely Simon

**Comment by sangwinc** [comment] 2021-12-22 15:20
Simon,

Thanks for contacting us.  93 PRTs and many inputs!  I never envisaged STACK would be used in this way, and so there is a "model" in my mind of how a question works.  This model did not consider code shared between PRTs in this way.  I'm not surprised your "maxima server is pretty exhausted when multiple students run those exercises simultaneously."  We do have some exciting changes which Matti has created to call Maxima only once for each student attempt, which will radically improve performance in situations like this.  These are in the pipeline.

A "common variable area" is a very sensible solution.  The problem is with (i) missing and (ii) "invalid" inputs?  What should happen then?  The whole design (model) is based around the following.  A PRT is executed when all the inputs upon which it relies are valid, and when a request to "check" is received.  Then, the PRT is given

1. the question variable values.
2. the value of the inputs relevant to that prt (automatically detected by the code)
3. the feedback variables.

The potential complexity is why we don't have a "check" button per PRT.  If a particular input is missing/invalid we'd have to decide what to do with any calculated values.

In the next version we will allow external code to be imported into (i) question variables and (ii) feedback variables.  This will solve the problem of maintaining common code in multiple feedback variable areas.  For this reason, I'm not in favour of a common area.

Would you be willing to show me your question, and demo what you are doing?  When someone has a use-case I didn't consider it is very helpful to try to understand the problem. There may be ways we can better support this.  If so, please email me at C.J.Sangwin@ed.ac.uk in the New Year and we could arrange a Zoom call to discuss how to proceed. I'd be very interested in understanding exactly what you are doing.

Chris

**Comment by aharjula** [comment] 2021-12-22 15:45
Well, the work that Chris mentioned should help the performance, though we would really need to see a question of this size to ensure that we actually can execute it in a single piece in the new system. As to shared code in external code, while it is a feature that might help to sync things over multiple questions it sounds to me like that would not work, as if the logic were similar in the PRTs you would probably have already just defined a common function implementing the logic in the question variables and simply included just the call to it in the feedback variables.

The scale of the question and the "step by step" nature sounds more like a Stateful question and it might be that Stateful would provide better tools for dealing with this. In it, you could actually take the steps and once the initial step has been done you could then calculate the correct values for the next ones and would not need to care about any possible changes to the earlier ones. It might even be simpler to author, than to deal with that many inputs and PRTs in a single place.

As before while there are now tools in a development version that would allow logic to know which inputs are in play I still think that sharing a common input processing for PRTs is not a thing that would fit the model and would berak its nice walls don't seem like a good thing. My earlier comments about placing logic at the input side for common preprocessing that could be used by multiple PRTs is likely to not help here either as with 40 inputs things are likely to not work.

That number of inputs sounds large, are there any that could be combined by using matrices or varmatrices? Or maybe Statefuls [data-entry](https://github.com/maths/moodle-qtype_stack/issues/555#issuecomment-583360406) input would help?

**Comment by Famondir** [comment] 2021-12-22 16:12
Actually, I'm realy looking forward to a version of Stateful that is ready to be delivered (and our Moodle admin is willing to install). On my test system a half year ago I did not made it to a working exercise. That would be realy an alternative.

In the new year I will test Prof. Kallweits solution to bind the values of mutliple inputfields into one list. Right now in each prt 20 inputs each get combined to a list. And I have some more ideas for small performance boosts using some of the functions made for lists.

I'm not the actual author of the questions but was asked if I can help improving the a) maintancability and b) performance or to look for an alternative system. I already asked the author if he has shown the tasks to you or if I get permission to do so and will definitley come back to you on this topic in the new year.

Great to hear that thee will come a possibility to import external code. This might solve another problem of ours where we copy code around different questions as well.^^'

Thanks for the fast responses so far.

**Comment by sangwinc** [comment] 2024-07-18 19:54
I appreciate the haven't really resolved this issue, but there will always be physical limits to the size of a question.  I'm closing this issue now.  Please raise a separate, more specific issue, if you'd like us to fix something else.

**Closed by sangwinc** 2024-07-18 19:54 UTC
