### ISSUE TITLE
Parentheses lead to incorrect marking of sigfigs

### ISSUE THREAD

**Issue by jmbragg** [maths/moodle-qtype_stack#405] opened 2018-09-23 18:54 UTC
Here's a question I've written.  If I enter the answer in exactly as the "A correct answer is" at the bottom suggests, it marks it wrong because the sigfig test fails:
![bad with parentheses](https://user-images.githubusercontent.com/4606870/45931734-0a837680-bf40-11e8-8292-c4b0c1543743.PNG)

If I remove the parentheses, it marks the same answer correct:
![good without parentheses](https://user-images.githubusercontent.com/4606870/45931740-1838fc00-bf40-11e8-8c85-4af7ace42ffd.PNG)

Interestingly the question testing seems unfazed by this...  The model answer in the question and the test input are exactly the same.
![question test](https://user-images.githubusercontent.com/4606870/45931751-5d5d2e00-bf40-11e8-91d6-2d3c6a0a2efe.PNG)

**Comment by jmbragg** [comment] 2018-09-23 19:08
It actually just seems to be related to negative numbers.  I did something similar with a positive quantity and it worked fine.

**Comment by aharjula** [comment] 2018-09-24 05:53
It is the combo of `-(...)` that breaks it, it should be able to easily deal with `(-...)` or `-...`. In theory this special case can be fixed in the current logic relatively easily, but a new parsing logic is coming and it will do this more elegantly i.e. it does not care at all about anything you wrap the float/integer into and can find even multiple floats/integers if need be. 

Chris, do you want to fix this for this issue or shall this wait for the big rewrite to get ready? You know where that is and so on.

Should you wish to fix this yourself the issue is [here](https://github.com/maths/moodle-qtype_stack/blob/master/stack/utils.class.php#L1021-L1024), whoever wrote those four lines failed to notice that the correct way to eat meaningless wrappers is at [line 1046](https://github.com/maths/moodle-qtype_stack/blob/master/stack/utils.class.php#L1046), you only need to eat anything in front of the number no need to worry about anything coming after it.

**Comment by sangwinc** [comment] 2018-11-01 18:07
Just catching up with issues.  I think we should push ahead with the new parsing logic.

**Comment by sangwinc** [comment] 2018-11-01 18:13
By adding in these test cases (the last of which currently fails) we won't forget about this issue when we develop the new parsing logic.

**Comment by sangwinc** [comment] 2020-04-13 10:10
Fixed in 4.3.

**Closed by sangwinc** 2020-04-13 10:10 UTC
