### ISSUE TITLE
Odd Rounding Feedback

### ISSUE THREAD

**Issue by jmbragg** [maths/moodle-qtype_stack#242] opened 2016-10-03 02:35 UTC
![weird rounding feedback](https://cloud.githubusercontent.com/assets/4606870/19026155/5737be38-88f0-11e6-9b1b-7e264e2372b1.PNG)

Can you tell me what triggers the "The accuracy of your answer is not correct. Either you have not rounded correctly, or you have rounded an intermediate answer which propagates an error." part of this feedback message?  Its confusing students in scenarios similar to this one because they think they've got the answer correct, except for the rounding when in reality they're just wrong.

**Comment by sangwinc** [comment] 2016-10-03 07:26
This is the answer test.  Examples of all the feedback generated by the answer tests are given by this script which you can link to from the "Healthcheck" script.  

https://github.com/maths/moodle-qtype_stack/blob/master/answertests.php

The "Quiet" option will suppress this.  Yes, it is often confusing to have the feedback, but it is much better to auto-generate and suppress it than for each teacher to try to work out how to generate this feedback.  

If this solves your problem, please close the issue!

**Comment by jmbragg** [comment] 2016-10-05 04:32
I appreciate the automated feedback.  I think it just needs to be cleaned up a bit.  I don't want to do Quiet as an option as long as the feedback is good.  So I looked at the NumSigFigs answer tests and I really think there need to be two different feedback messages here.

For example (from the answer test suite)
SAnswer: 1.234
TAnswer: 4
This student has worked the problem wrong.  They will be confused by "The accuracy of your answer is not correct. Either you have not rounded correctly, or you have rounded an intermediate answer which propagates an error." and think they have just made a rounding error.  If the second sentence of feedback there were eliminated, then this would be fine.  Although at that point, its probably easier not to show any feedback at all because all you'd be saying is "Your answer is wrong" which its already been marked as wrong by Moodle.

Next:
SAnswer: 3.141
TAnswer: 3.1415927
Here the feedback message about rounding is useful.  This student has clearly solved the problem correctly but has just truncated their answer instead of rounded.  The current feedback message is useful.

So my proposal (without knowing how to organize this on the code side at all...)

1 - Check the number of sigfigs. (the X term in the [X,Y]

- If the number of sigfigs matches what is specified in the test options then it passes.

- If the number of sigfigs does not match what is specified in the test options, the test fails and the ATNumSigFigs_WrongDigits note is applied and the "Your answer contains the wrong number of significant digits." feedback is displayed.

- This is NOT a change from current behavior.

2 - Check how many of the digits are the same as the Teacher Answer (the Y term in the [X,Y] test option)

- If SAnswer has Y digits the same as TAnswer then it passes.

- If SAnswer has Y-1 digits the same as TAnswer then it fails, appends the ATNumSigFigs_Inaccurate note and displays "The accuracy of your answer is not correct. Either you have not rounded correctly, or you have rounded an intermediate answer which propagates an error." as feedback.

- If Sanswer has <Y-1 digits the same as TAnswer then it fails, and is just marked as wrong with no feedback.

- This is a change from current behavior.

- Obviously some thought needs to be given to someone using [2,1] as the test options.  I'd say that if Y-1 = 0 then just mark things wrong without adding any feedback.

**Comment by sangwinc** [comment] 2016-10-07 09:55
This sounds quite sensible.  Always very useful to have a clear statement from a practitioner!  I'll look into this.
Chris

**Comment by dhilsen** [comment] 2016-10-11 17:49
**I.**  I would agree the proposed changes are good ones. I should add that in the approach we use this is not an issue. We use one node to check the accuracy of the student answer, generally using the UnitsRelative test, and another node to check the number of significant figures using the NumSigFigs test. We want to check that (1) the student has the correct numerical answer within a tolerated percentage of error, (2) the student has entered the correct unit, and (3) the student has reported the answer to the correct number of significant figures. We can then assign different scoring weightings to these different aspects of the students answer. We assign a relatively minor deduction if the student enters too many or too few significant figures.

This is why I've been proposing the NumSigFigs test with a test option of "[x,0]"  ( i.e. [2,0]  [3,0] [4,0]. . .)  would only check the number of significant figures in the student answer and ignore the numerical value. This would give us a true and singularly-focused significant figures test. This comes in particularly handy for handling student answers with varying units. If the accepted student answer is 125 km or 125000 m, a single node with the UnitsRelative test would evaluate the numerical answer and unit, and an additional node with the NumSigsFigs [3,0] test would evaluate if the correct number of significant figures were entered for either answer regardless of the unit. 

Would other STACK users in the field of science find this useful?


**II.**  An additional issued needs to be mentioned. Currently, the NumSigFigs test does not properly identify significant figures. The following tests show the problem. Here we used the NumSigFigs answer test with the Test Option setting [3,1]. We focused solely on testing if 3 significant figures could be correctly identified in the student answer, and were not concerned about the accuracy of the student answer. 

**Test cases performing CORRECTLY (checking for 3 significant figures):**
1) The test DOES recognize final zeros preceding the decimal as non-significant.
(Example: TAns answer 1174.43;  SAns answer 1170 evaluated as correct)
(Example: TAns answer 61250;  SAns answer 61300 evaluated as correct)
2) The test DOES recognize when too many non-zero significant figures are entered.
(Example: TAns answer 1251.65;  SAns answer 1252 evaluated as incorrect)

**Test cases performing INCORRECTLY  (checking for 3 significant figures):**
3) The test DOES NOT recognize too few significant figures being entered.
(Example: TAns answer 178.35;  SAns answer 180 evaluated as correct)
(Example: TAns answer 33.1558;  SAns answer 33 evaluated as correct)
4) The test DOES NOT recognize final zeros after the decimal as being significant.
(Example: TAns answer 1.5;  SAns answer 1.500 evaluated as correct)
(Example: TAns answer 245;  SAns answer 245.0 evaluated as correct)

After looking over posts in other forums pertaining to significant figures, it appears there may be some fundamental misunderstanding regarding significant figures, perhaps arising from differences in the fields of science and mathematics. Can we come to agreement that in the field of science the following rules should be used to identify significant figures?

Rules for Significant Figures:
1) Non-zero digits are always significant.
2) Any zeros between two significant digits are significant.
3) A final zero or trailing zeros in the decimal portion ARE significant (i.e. for the number 5.500 the final two zeros are significant).
4) A final zero or trailing zeros in numbers with no decimal point are NOT significant (i.e. for the number 5000 the final three zeros are not significant, if we wanted to make the final three zeros significant we have to use scientific notation 5.000 x 10^3).

**Comment by aharjula** [comment] 2016-10-12 07:08
Hmm... I was under the impression of `[y,x]` in SigFigs meaning look for `y` accept `x` and the typical use cases would be to have `[y,y]`, `[y,y-1]` or `[y,y+1]`. The idea for `[y,0]` makes sense and I think it is coming. 

As to the rules of significant digits, we have technical difficulties there as the parsers turn all of the numeric values to floats or integers and when they are converted to floats we lose the information about actual digits present, especially trailing zeros after a decimal point. However, we have a plan for fixing that at a higher level of parsing and it might appear at some point in the not too distant future. But there is one little issue that is still presenting problems for that basically the edge case of zero combined with requirements for a number of significant digits, might appear when randomised question generates a case where the value to be entered actually is zero while the evaluation logic wants certain number of significant digits. My current thinking is that for a zero value all the zeros are either significant or or unknown like the zeros in your rule 4, they can be significant if the value has a zero there.

For that edge case I would need someone to confirm this thinking about significant digits as correct:
1. `0.0010` has exactly 2 significant digits.
2. `100` has at least 1 and maybe even 3 significant digits
3. `10.0` has exactly 3 significant digits
**4. `0` has 1 significant digit
5. `0.00` has at least 1 and maybe even 3 significant digits**
6. `0.01` has exactly 1 significant digit.

I.e. in my examples the cases 4 and 5 are there to provide a "false positive" and a way out of the situation where a zero value would need to be given at a specific accuracy. Is this an acceptable way of interpreting the various rules of significant digits? Or do you want us to consider those cases 4 and 5 to have 0 significant digits like the common rules say and leave handling of the inconvenient zero case for the question author. Or maybe we should just allow zero to pass all sigfigs tests related to significant figures?

**Comment by sangwinc** [comment] 2016-10-12 09:05
Thanks Matii,
These are really helpful test cases.  If we can agree on a design for this it will also help with the "decimal places" test which has very similar issues.

**Comment by sangwinc** [comment] 2016-10-12 11:00
I've added in an option for [n,0], but this really only is able to test if

`SA=significantfigures(SA, n).`

This is fine without trailing zeros, but with the test cases which Matti highlighted above (added in this commit: https://github.com/maths/moodle-qtype_stack/commit/f0182fabd53845c4102ef982e3d5e1132446bb41) we now have a lot of failing unit tests.  I think we will need to combine this with the decimal places code at some point soon to fix all this.

I do appreciate the test-driven and example-driven discussion.  Please add more examples, and we will work towards accommodating all the test cases in the near future.

**Comment by dhilsen** [comment] 2016-10-12 19:18
Thank you Matii for taking time to explain the technical difficulties associated with significant digits, especially with trailing zeros. Your efforts in addressing this issue are very much appreciated!

Below I provide my thoughts regarding your statements concerning significant digits. Here I am merely stating the standard rules of significant digits and how these numbers should be evaluated if entered by a student.  
1. 0.0010 has exactly 2 significant digits.
This is correct.
2. 100 has at least 1 and maybe even 3 significant digits
100 has precisely 1 significant digit. It would need to be stated as 1.00 x 10^2 in order to have 3 significant digits. This is quite important if we're to follow the standard rules.
3. 10.0 has exactly 3 significant digits
This is correct.
4. 0 has 1 significant digit
I believe this is acceptable.
5. 0.00 has at least 1 and maybe even 3 significant digits
I believe this is acceptable. 
6. 0.01 has exactly 1 significant digit.
This is correct.

Answers which are equal to zero do pose a bit of a problem. My preference would be to allow zero to pass all sigfigs tests related to significant figures. This may be the safest way to proceed as instructors generally grant leeway to students when it comes to significant digits and an answer of zero.

**Comment by aharjula** [comment] 2016-10-13 06:54
As to that 100 having precisely 1 significant digit case, it is indeed true that when we present measurement values to the student then that has exactly 1 significant digit, but do we generally assume that the student is presenting measurement values to us? Basically, if we present values 48 and 52 to the student we are saying that the we have two values with two significant digits, now it we expect the student to sum those we know the result must have the value of 100 and it must be presented how? I would go for 100 but 10.0e1 and 1.00e2 are probably both right if I remember the rules right, the point here being that the first one does not demonstrate that the student knows which significant digits are needed but it is the "natural" way of presenting things. Is it reasonable to assume that the student should present that end result with the same rules as a measurements or do we generally allow simpler rules to be applied?

I fear `significantfigures(a,b)` might not actually work according to those rules so good that this came up.

I would still rather interpret `100` to have 1 and maybe up to 3 significant digits and thus be merciful in the general cases i.e. let it pass SigFigs=100 with `[3,b]` where `b in [0,1,2,3]` and maybe have `b=-1` to provide a way to test for that presentation of actual measurement value case i.e. the strictest case.

I am not a teacher of anything, but my understanding is that there are multiple sets of rules and the strictest ones are related to the presentation of measurement values while generally end results are preferred to be presented in concise forms i.e. move the powers of ten to the prefixes and minimise the distance of the numeric part from unity. Naturally, there are more artistic freedom for the presentation of those end results, as long as that presentation does not generate extra precision from somewhere. I think I was taught to aim for numeric values between 0.5 and 5000 in the presentation of the end results, but it was long ago and I have no idea if that is true (if there even are any real rules), but it does conflict with the presentation rules of measurements in some sense as it does allow trailing zeros in front of the decimal point even in cases without decimal points.

**Comment by dhilsen** [comment] 2016-10-13 20:40
There's no doubt that dealing with zeros and significant figures can sometimes be a thorn in the side. Some instructors and textbooks do bend the rules from time to time. For example, in a problem such as find Usain Bolt's velocity if he runs the 100 meter dash in 9.58 seconds, it might be assumed that 100 meters is a precise measurement with 3 significant figures, so it's acceptable to express the answer as 10.4 m/s instead of 10 m/s. I do want to stress that an assumption is being made here, and in these cases textbooks and instructors do need to tell the student in advance what assumptions are being made.  

The approach of being merciful and interpreting the number 100 to have 1 and up to 3 significant figures does have some appeal. However, are we saying that zeros in all such numbers (final zeros in numbers with no decimal point) will be counted as significant? Does this mean that the number 5000 could be interpreted to have 1, 2, 3, or 4 significant figures? Would the number 2500 be interpreted to have 2, 3, or 4 significant figures? If this is the case, I would have some reservations about using this approach.

The question was raised "is it reasonable to assume that the student should present the end result with the same rules as measurements or do we generally allow simpler rules to be applied?" In the field of science the student should most definitely present the final answer using the same rules as applied to measurements, in other words, present the final answer following the rules of significant figures. The final answer should express no more, or no less, precision than the limiting value used in the calculation. The rules are pretty cut and dry: (1) the final result of multiplication or division should have only as many significant figures as the number with the least number of significant figures used in the calculation, and (2) when adding or subtracting numbers, the final result is no more precise than the least precise number used (least number of decimal places).

In my opinion, the NumSigFigs test should be made to strictly follow the rules of significant figures. This way instructors will know exactly what to expect from the test. This also allows instructors to flex the rules as they so choose. Note that in no way do we need to enforce the rules for multiplication/division and addition/subtraction, we only need to uphold the rules for IDENTIFYING the number of significant figures in a student answer. The instructor will make the determination of how the many significant figures should appear in the student answer using the NumSigFigs test option setting.

In the Usain Bolt example above, if the instructor wanted students to assume 100 meters has 3 significant figures and the answer should be 10.4, the NumSigsFigs test option would be set to [3,2] or [3,3]. If the instructor wanted to strictly follow the rules of significant figures and only accept an answer of 10, the NumSigsFigs test option would be set to [1,1]. If the instructor felt both answers were acceptable, then two nodes could be setup in the PRT using the different test options. Note that for this approach to be successful the NumSigFigs test has to strictly follow the rules for identifying the number of significant figures in a student answer. This system would perhaps allow for the greatest amount of flexibility.

**Comment by aharjula** [comment] 2016-10-14 07:18
As a background STACK has been used in engineering teaching for physics and electrical engineering within HUT (now Aalto University) with SigFigs test (first implemented here) and units (first implemented here) for over six years (longer for maths) pushing around 600 students (more if maths included) a year through materials using those features and having a material pool using that kind of a lenient thinking nearing 500 questions (complex questions with randomisation which would not react well to sudden overt strictness). So engineering was there first pure science is just coming here and we engineers have defined the first rules don't go changing them so that you break our materials.

Strictness has its place and I am not saying it should not be possible to enforce it, what I am worried here is the fact that I have looked over very good and smart STACK question authors for a decade now and the way they manage to combine various tools together forgetting how they interact when combined with randomised parameters and how often we get situations where people cut themselves with too sharp tools. In my opinion the SigFigs test in its current somewhat fuzzy form is suitably blunt to be used in reasonable use-cases without causing too much grief. And I would imagine there would be trouble if we were to switch the test to be absolutely strict when using the current testing parameters used in legacy materials.

Having talked about this with physics teachers they consider absolute strictness handy in some cases where we teach and test it, but consider it as bullying the student in the general cases i.e. they would not require those significant trailing zeros to be presented in unambiguous way (i.e. 100 works for them just as well as 1.00e2) in questions that are not focused on just significant digits, though otherwise the digits must match, no extras or lost ones and so on.

As to how many significant digits 100 has, it has 1 but if we are testing for the presence of 3 and our value happens to be of the form that has significant trailing zeros I want to be lenient by default and consider those zeros there to be significant from the point of view of that test, if you wish to be absolutely strict and only accept that to be given as 1.00e2 then you should instruct the test to be extra strict. Note that "value happens to be" we are focusing on randomised questions here and if most of the random variants do not lead to trailing zeroes but some do and students getting those variants need to find out that extra strict way of inputting things, or we can just be lenient be default.

And indeed STACK will never work out how many digits the answer should have on its own and that detail will be question authors task to give it as is the task of ensuring that it matches the random parameters. _As a side note are you sure about those rules about adding and subtracting?_

**Comment by sangwinc** [comment] 2016-10-14 09:37
Thanks Matti, David,

You are correct to remind us all of the dangers of changing existing functionality, as is David that we should strive to get this all "right"!

We could address the first of these by saying that we have "StrictSigFigs" for a very strict interpretation, (100 has 1 sig fig, 1.00e2 has 2)  and keep "SigFigs" for the current (more liberal) situation (100 to 3 sig figs is not marked "wrong").  Even if we do this, the current test does not deal well with trailing zeros and I think we should seek to improve this.

Is anyone aware of research in the physics education literature about students' and teachers' understanding of these issues?  It occurs to me this must be a serious issue which has attracted research effort to understand before.  We should look at this before we rush to code...

Chris

**Comment by sangwinc** [comment] 2016-10-14 18:50
This is relevant:  http://img.21food.cn/img/biaozhun/20090815/187/11183606.pdf

**Comment by aharjula** [comment] 2016-10-14 19:34
Ok. so 3.1.4.3 of that pdf is the bit that I am arguing, that "may" is something that we here at Aalto want to keep as a "may" instead of a "must", but there is a reason for the "must" variants existence we just oppose the current test turning to it.

**Comment by jmbragg** [comment] 2016-10-14 20:27
Well I've stayed out of this because I've been busy this week.  I think it would be a bad idea to suddenly start enforcing the 100 = 1sigfig interpretation.  That is certainly not a consistent rule here in the US.  I just took a quick peek at 4 different introductory chemistry texts that are popular and all of them said that the number of sigfigs in 100 was ambiguous and that the meaning was unclear.  Several were clear that it should only be 1 sigfig but said as a practical matter it would be assumed to be ambiguous.  

There is also the issue of "100.".  That's a typical way of saying, this has exactly 3 sigfigs.  Is that going to be included?

I say all of this to say, I'm perfectly happy with some degree of generosity in the sigfigs test.  Sigfigs are a useful tool, because they're quick and easy and give decent answers.  They're not the exact right answer on how to do error propagation though. So I think its silly to get overly picky about how exact we're being with applying the rules of our approximation technique.

The wars over sigfigs in the chemistry world are real.  Its best to leave it generous to provide the most use for the most people.

Matti, those rules for addition and subtraction are the ones that I've always seen too.  But they're also a good example of why sigfigs as a general rule are just an approximation.  After all, why should 3.00+3.00+3.00+3.00 = 12.00 when 3.00*4.0000000000000000000 = 12.0

**Comment by dhilsen** [comment] 2016-10-14 20:30
I would agree that it is of utmost importance that existing STACK questions do not become broken by changes to the SigsFigs test. The proposal made by Chris seems to be an ideal solution: keep the existing "SigFigs" test in its present form, and add a new "StrictSigFigs" test which would strictly follow the standard rules of significant figures and what those rules say about zeros used as placeholders. This would allow the instructor to make the determination of what role significant figures should play in evaluating the student answer.

In my view, having the two SigFig versions would be important due to the fact that instructors can be quite varied on how rigorously they adhere to the rules. Some instructors I've spoken with are very rigid regarding significant figures throughout an entire introductory physics course, others are rigid during the first several weeks of the course and then back off. Each and every instructor has their own approach and I feel it would be wise to accommodate those varied approaches.

**Comment by dhilsen** [comment] 2016-10-14 21:15
I certainly don't want to drag out this discussion on significant figures, however, I wanted to get back to my original discussion point concerning what are perhaps the two most important issues: 

NumSigFigs [3,1] Test cases performing INCORRECTLY (checking only for 3 significant figures):
1) The test DOES NOT recognize too few significant figures being entered.
(Example: TAns answer 178.35; SAns answer 180 evaluated as correct)
(Example: TAns answer 33.1558; SAns answer 33 evaluated as correct)
2) The test DOES NOT recognize final zeros after the decimal as being significant.
(Example: TAns answer 1.5; SAns answer 1.500 evaluated as correct)
(Example: TAns answer 245; SAns answer 245.0 evaluated as correct)

Can others confirm they are experiencing these two issues? If so, perhaps we could discuss whether these fixes should appear in the existing "SigFigs" test, the newly proposed "StrictSigFigs" test, or both.

**Comment by sangwinc** [comment] 2016-10-15 16:33
First, thank you to everyone for your very helpful comments.  Having the unit tests specified in advance, and with the very helpful contribution of PHP code from Matti, I have refactored the numerical tests.

I hope I have correctly added support for trailing zeros in all the numerical tests which need them (NumSigFigs, Units, UnitsStrict).  I hope the new answer test StrictSigFigs does what it should!

I have added in the tests people mentioned above (including "100." and the tests David added).

The proposed behaviour of STACK is now embodied in these tests 
https://github.com/maths/moodle-qtype_stack/blob/ATUnitsNum/tests/fixtures/answertestfixtures.class.php
Please let me know of anything you *don't* like.

I have tried, as far as reasonable, not to change the NumSigFigs test.  *BUT* I agree that it did contain bugs in not dealing with trailing zeros and I hope I have fixed these.  I intended to.

There is new documentation which I hope correctly records both this discussion and what I have implemented. 
https://github.com/maths/moodle-qtype_stack/blob/ATUnitsNum/doc/en/Authoring/Answer_tests_numerical.md

Please raise objections to the new behaviour.  I think I've done enough for one weekend (although I've used a dreek Edinburgh Saturday to good effect), so I'll pick this up on Monday!

**Comment by aharjula** [comment] 2016-10-15 16:56
Looks interesting, waiting to see how `UnitsStrictSigFigs` works from the technical implementation side.

**Comment by sangwinc** [comment] 2016-10-15 20:42
Good point Matti,
Thank you for catching this before the code gets embedded.  I've refactored to make the inclusion of two more answer tests sane.  `UnitsSigFigsStrict` and `UnitsStrictSigFigsStrict.`

Does anyone actually need these two answer tests? 

- `UnitsSigFigsStrict:`   require strict interpretation of significant figures (e.g. 100 has 1 s.f.) but condone compatible units.
- `UnitsStrictSigFigsStrict.` require strict interpretation of significant figures (e.g. 100 has 1 s.f.) and require the same units as a teacher.

Perhaps we should confirm the other changes are satisfactory before adding these additional tests?

**Comment by sangwinc** [comment] 2016-10-16 09:19
Joshua has added a number of test cases (the above commit).  All these tests pass except for the last one which fails.  I think this resolves issue #232 for now, but there are insuperable problems in making very fine-grained distinctions between floating point numbers on finite state machine!

https://github.com/maths/moodle-qtype_stack/commit/724828ef8422ac55ba62a1fab74b25f6d5fe048a#diff-f4f096073526e9152ea09b882735e216R1148

Here the student has responded with "9.8e-9*mg".  The teacher will accept 3 significant figures, two of which need to be correct.  Since the student has only responded with 2 significant figures, the test has rejected it with the note "ATUnitsStrictSigFigs_WrongDigits."   I consider this as the correct behaviour for this test.  While the teacher will accept a rounding error in the last digit, the student should have at least supplied it.  I'll therefore correct this test to reflect this design decision.  Comments welcome from teachers who use this feature please.

**Comment by jmbragg** [comment] 2016-10-16 10:27
Chris, just making sure... Those all pass for you on the latest code?  Most of them were failing for me when they were in my question.  I didn't know that there were changes that had been made that cleaned some of this up already.  Or is there an issue with the question itself...

**Comment by sangwinc** [comment] 2016-10-16 20:29
Yes, the latest code in the ATUnitsNum branch.  The question works and all the tests pass, as do all your "question tests" on all deployed variants.

I'm currently aware of only one outstanding issue:  when a student validates an answer with a trailing zero e.g. "1.00m/2" maxima truncates the digits to "Your answer was ... 1.0 m/s".   This is due to the same issue in Maxima and the way it deals with and displays floating point numbers.

**Comment by dhilsen** [comment] 2016-10-17 21:19
I have tested SigFigsStrict and it seems to have resolved most issues we were experiencing with the previous SigFigs tests. Of great importance is the fact that the test does now recognize non-significance of final zeros in numbers with NO decimal. The test also recognizes when too few significant digits have been entered which previously was an issue. 

However, the testing I have done seems to show that one critical issue still remains: final zeros appearing after the decimal are not being recognized as significant.  
Example: SigFigsStrict with test option set to 3
TAns answer 15.1 ; SAns answer 15.10 and 15.100 evaluated as correct.

**Comment by sangwinc** [comment] 2016-10-18 10:31
Right, 
Thank you for spotting this. 

All these problems (right from the word go) are caused by Maxima stripping off trailing zeros in floats.

In the potential response tree we all comparisons of *any* expression, which might or might not, depend on calculations based on the student's answer.  When we construct the PRT we run the student's answer through the CAS, otherwise we would not be able to perform such calculations.

This means that, even though the *answer test* did not have the but you reported above, the student's raw answer is modified before it gets to the test, stripping off the zeros and creating a false impression the test does not work.

My suggested fix to this is that, if the input to the answer test is the name of an input (e.g. "ans1") then we use the casvalue of the input, not the computed value from the CAS session.

See https://github.com/maths/moodle-qtype_stack/commit/7cc830f5c244252e76d032ee5876df34aac8edae#diff-6b2fb89ba46f0aa50d67916fec0f4c3bR221

Note also the "question tests" suffer from exactly the same issue.
https://github.com/maths/moodle-qtype_stack/commit/7cc830f5c244252e76d032ee5876df34aac8edae#diff-1f63f418790d6b2410777c26bed1d36cR136
I've not had time to address this today either.

I'm in a real hurry today (flight to catch...) and so I apologise in advance that I've not had time to run the existing unit tests on these changes.....   This may break something else so beware of this branch until we have tested it more.

We are making steady progress.  I sometimes wonder if I'd written my own CAS in the first place if I'd have more or fewer similar woes to the trailing zeros issues and all the consequential work-arounds!

**Comment by jmbragg** [comment] 2016-10-25 01:15
Chris, just checking in on the status of things...  I'm getting ready to get to a point in my course that requires calculating tiny numbers again (energies of individual photons) and wanted to get newer code to use to incorporate some of the fixes you've made lately.  I see all this activity is in the ATNumUnits branch.  Does it seem safe/recommended to you go ahead and give the code a whirl in production?  I still have two weeks before I'd like to use it but just wanted to go ahead and check in while I was writing those questions and thinking about it...

**Comment by sangwinc** [comment] 2016-10-26 19:13
Yes, I've been working on making sure the new features don't break any old ones (they did....) and have refactored the code accordingly.   Because of this I'm trying to test this as much as possible before I merge into master.

If you (or anyone else) has large question banks, I'd really appreciate you testing your existing questions on the code in the ATNumUnits branch. If you have written question tests then you can batch run all these from the question test bulk script.  (Available from the question type config page).

I did have a couple of issues with existing questions, so I'd appreciate some other people testing this as well.

I have nothing left to do (new features) in this branch except fix a couple of broken tests and add a lot more.  As soon as people are happy I'll merge to master, tag and release these officially.

**Comment by sangwinc** [comment] 2016-11-04 17:32
Ok, apart from testing I know of nothing which needs to be done.  Please reopen this issue if needed...

**Closed by sangwinc** 2016-11-04 17:32 UTC
