### ISSUE TITLE
significantfigures(a,b) function

### ISSUE THREAD

**Issue by dhilsen** [maths/moodle-qtype_stack#245] opened 2016-10-26 17:42 UTC
With the significant figures tests working so well and able to handle the difficult issue of trailing zeros, it seemed logical to ask if the significantfigures(a,b) function could be made to do the same. I believe this function presently truncates to the specified number of significant digits but does not recognize zeros after the decimal as significant (i.e. with the function set to display 3 significant figures, a value of 1 is displayed as 1 and not 1.00 as would be expected). 

Having this functionality would be extremely important as random variables and the teacher answer would be displayed to the student with the correct number of significant figures.

**Comment by sangwinc** [comment] 2016-10-26 18:11
David,

There are two separate issues here.
(1) rounding of numbers to the correct value.  That is what significantfigures(a,b) does.
(2) display of floating point numbers to the correct number of significant figures, including trailing zeros.

We do *not* propose to have the maxima value carry around information about the number of significant figures it represents.  I (now) understand that physics people use the notation 1.00e2 to represent *both* the value 100 and the fact this is correct to 3 sig figs.  

We are not going to add this to Maxima.  The teacher will have to keep track of this kind of thing as the functionality required to do this would be major.  In fact, since we are relying on the underlying LISP version, we'd need to re-engineer LISP.

Does this make sense?

**Comment by dhilsen** [comment] 2016-10-26 19:03
Thanks Chris, what you described makes perfect sense. I was curious if there might be a way to make this sort of thing a display property only and not have Maxima carry around the significant figure information. With regard to displaying random variables to the student, could there be a function utilized in the text portion of the question that would simply display a specified number of significant figures for the random variable (including trailing zeros)? 

Presently, we use dispdp(a,b) in the text portion of the question to attempt to display the correct number of significant figures. This works as long as the number of digits remain constant for all random variables. For example, if we want 3 significant digits to be displayed to the student and have random variables 1 - 9, we can select to display 2 decimal places and get 1.00, 2.00, 3.00 . . . However, if we want to display random variables 8 - 15, we get 8.00, 9.00, 10.00, 11.00 . . . with the resulting problem of the number of significant digits changing from 3 to 4.

**Comment by jmbragg** [comment] 2016-10-29 15:04
I just updated to the latest code in the ATNumUnits branch and ran all the question tests in bulk. I did get some failures because I have used significantfigures() in my question tests. So the combination of the better sigfigs checks and the fact that significantfigures(0.179854,3) gives 0.18 means that the test fails for that particular one.

**Comment by jmbragg** [comment] 2016-10-29 17:49
I've looked through a pretty substantial portion of my test failures now, but not all of them.

I currently have 1024 variants of STACK questions at the moment.  Of those, 78 question tests failed after the upgrade.  All of the ones that I looked at were examples where I used significantfigures() in the formula for the answer test and it had left off a trailing zero behind the decimal point causing the answer to fail to match the correct number of sigfigs.

Is there a better way to write the question test to avoid this problem?

**Comment by sangwinc** [comment] 2016-11-01 07:35
Thanks,

I think this is a case of "we've fixed the problems with sig figs" (it was
very sloppy in the past) and now we have to fix the incorrectly passing
unit tests.

This is going to be a headache.  The problem is that the *value* of the
number doesn't have trailing zeros...  I'll give this some thought.  I'm
committed to unit testing, so we need to fix this.

If there are genuine bugs in STACK which a student might see, these will
take priority, but I'll try to sort this our before the release.

Chris

**Comment by sangwinc** [comment] 2016-11-14 15:47
I've (finally) managed to find a mechanism to get Maxima to print out trailing zeros in numbers.

This has been a real slog.  Indeed, I can't remember quite such an awkward issue in many years with STACK, but this had to be done.  

Now, we have a new field being created by Maxima called the "dispvalue"  See here.
https://github.com/maths/moodle-qtype_stack/blob/ATUnitsNum/stack/cas/casstring.class.php#L55

When a variable is created we how have the "value", as before this will be the thing which we type in again.

Now we have a "sanitised value" which can be used for the teacher's answer, and the testing.  If you use "dispdp(x,n)" then the sanitised value should be "x" to "n" *printed* to "n" decimal places, trailing zeros and all.  If you have existing answer tests, you can create values with trailing zeros from this.

Please could people run this new code on their existing question banks, and have a look at the attached question (will only work with the new code).  No serious problems (I expect some bugs...) and I'll merge with master.

I think this is a big step forward here....
[questions-Scratch-Random sigfigs-20161114-1230.xml.zip](https://github.com/maths/moodle-qtype_stack/files/589727/questions-Scratch-Random.sigfigs-20161114-1230.xml.zip)

**Comment by dhilsen** [comment] 2016-11-14 16:39
Thanks Chris, this is a wonderful addition to STACK. You mentioned the syntax for "dispdp(x,n)" in your post, could you please clarify the syntax for "dispvalue". Thank you!

**Comment by dhilsen** [comment] 2016-11-14 16:43
I may have misunderstood things, is "dispvalue" a field and not a function?

**Comment by sangwinc** [comment] 2016-11-14 19:20
Good question David,
"dispvalue" is an internal field in the casstring object.  Question authors will have no direct access to this!  Sorry for the confusion.
Chris

**Comment by jmbragg** [comment] 2016-11-14 20:29
Your referenced that dispdp() will display the correct number of decimal places.  Will significantfigures() do the same?  I'm assuming so.  If that's correct, then I won't have to change a single answer test in my course... :)

**Comment by aharjula** [comment] 2016-11-15 07:09
If I understood correctly the way to display with significant digits is `dispsf(v,n)` and `significantfigures()` is for rounding/chopping to specific length for calculations, the disp functions do not work with calculations as they run at the string generation layer and the rounding functions do not affect display as they can't tag the numbers with the necessary metadata. But in any case with `dispsf()` we were able to present the teachers answers correctly and even get question tests to pass.

**Comment by sangwinc** [comment] 2016-11-15 08:03
I've added in an extra layer for "sanitised value".  This will only be used for a very small number of tasks.  Currently this layer is only used for (1) generating the teacher's "correct answer" (e.g. "fill in correct response") and (2) generating the values for the question tests.

This sanitised layer strips out presentation functions, such as "stackunits" (goes to multiplication) and "texcolor" and creates a value which could be typed in (by a student actually).  

The CAS has to carry around information about decimal places with the value.  If you use the "dispdp" function you have a Maxima expression such as "dispdp(3.1,2)" which will be displayed with TeX as 3.10, the "value" will be "dispdp(3.1415,2)" and the sanitised value will also be "3.10".

The value, "disdp(3.1,2)" is a maxima expression with operator "dispdp" and arguments [3.1, 2].  I have no intention (at this stage) of adding rules to the simplifier about how to manipulate these expressions in arithmetic. That would be an interesting (and non-trivial) mathematical project.  So, "disdp(3.1,2)+2" will be unsimplified. 

I want to sit on this and think about the design for a couple of days.  In particular, I think I should do the following

(A) a suite of functions which calculate and round the value, and return just a float for further calculation
 - significantfigures
 - decimalplaces

(B) functions which signify the value and its accuracy, and round the input
 - dispdp [WARNING: I've realised this morning this function has changed its behaviour in the latest commit and no longer rounds its argument.  I'll change this back...]
 - dispsf

(C) functions which strip out all presentation, and use these in for example the answer tests.  We do want to compare dispdp(3.14,2) with 3.14 at some point the teacher should not worry about this.

I think this santised layer is a good design, and would have saved a lot of fussing about earlier, with things like the "stackunits".  There we are.  Now would be a good time to comment on the design of all of this, and any problems all this might cause with existing questions.

**Comment by jmbragg** [comment] 2016-11-15 17:55
Ok... So I guess I'm still not understanding what my answer tests should look like now...

Say an answer to a question might be a question variable "answ" (which is an unrounded float) with units of kJ that I want rounded to 3 sigfigs.  Currently my answer tests are in the style of
`ev(significantfigures(answ,3)*kJ,simp)`
These work fine except for answers with trailing zeros.  

Would my new answer test then be:
`ev(dispsf(answ,3)*kJ,simp)`

But Chris seems to be saying that dispsf(answ,3)*kJ won't be simplified...

Sorry if I'm being dense here but I just want to make sure I understand what's going on and what I'll need to change to get all the answer tests working.

**Comment by aharjula** [comment] 2016-11-16 07:21
I don't understand what you would do in an answer-test that would require `ev(dispsf(answ,3)*kJ,simp)`, so I'll paint a very detailed picture of the way I understand where and how you are supposed to use `dispsf()` vs. `significantfigures()`.

Now suppose you have a question that asks for the area of an rectangle with sides `a` and `b` defining the area and those have been measured with different precisions and will be presented with different number of digits. To start with you use some form of randomisation to generate two floats giving those lengths:

```
a:0.5432325
b:1.348985
```

Now obviously you are not going to give any measures at that level of accuracy so in the question text you will have `@dispsf(a,4)@` and `@dispsf(b,3)@` or more likely as there are units here you would have `@stackunits(dispsf(a,4),cm)@` and so on, you could also have that defined in the question variables as `dispb:stackunits(dispsf(b,3),cm)` and referenced in the text just as `@dispb@`. But now comes the point where you need that other function.

To calculate the actual area you can't just say TA:a*b as a and b have more precision than what you have shown to the student and you can't ask for something they could not know. The problem being that you can't do arithmetic with the dispsf() definitions of displayed values so you need to do rounding to the displayed accuracy. So:
``` 
TA:a*b /* 0.732812494013 */
TA:significantfigures(a,4)*significantfigures(b,3) /* 0.73332 */
```
And again `TA` is a raw number with no accuracy so we need to define the accuracy so that we can plug this in to the inputs "Model answer" field. Or to the question tests...
```
dispTA:stackunits(dispsf(TA,3),cm^2) /* 0.733*cm^2 and some tex for the spacing */
```
And the what do you do in the answer test? Depends on the test you are using. Assuming the students answer comes form an Units type of an input field named `ans1` we could simply use "UnitsSigFig" as the test and place `ans1` to the students answer field and `TA*cm^2` to teachers answer field and `3` to the test options and that would be enough as the test returns (atleast it has done so in the past) the teachers answer to the correct presentation for testing.

But for some reason your tests seem to round the students answer (if `answ` is the students answer that is, used to naming convention that teachers answers always start with `t`) if it is the teachers answer keep on using 'significantfigures()' there as `dispsf()` will not work there.

**Comment by sangwinc** [comment] 2016-11-16 10:35
Thanks Matti for answering this.

Yes, the intention of the current design is to use "dispsf" and "dispdp" at the last moment for display as you explain here.

Do people accept this design as sensible and useful?

**Comment by dhilsen** [comment] 2016-11-16 18:06
Chris, the design you proposed sounds very sensible and would nicely meet our needs. Thanks again for your dedication to making STACK so robust in the field of science.

**Comment by jmbragg** [comment] 2016-11-17 05:33
First, I got my nomenclature wrong.... I was talking about the question tests.  

I think part of the issue here is I'm still trapped in some old ways of thinking about building questions when Chris and Matti have been quite busy improving the entire system.  For example, I think I first played with this back in the days of `stack_units_split`.  In particular, I don't think I had wrapped my brain around the necessity of the `stackunits()` function.  But I see it now...  Thanks for being so patient with me and explaining.

Matti, one place that seems odd to me that you would do it that way is `@stackunits(dispsf(a,4),cm)@` in the question text.  It seems far less complicated to just do `@dispsf(a,4)@ @cm@`.   Is there some reason why you suggest your method?

In any case, there are now more things that I'm wondering if I'm doing them in the way its intended to do them.  I'm going to apply this new understanding to my next unit's questions in the next few weeks.  I'll post them over on Moodle.org and hopefully one of you all would be willing to do a bit of code review with me.  Hopefully some of the best practices there can migrate their way into a Units question authoring guide similar to the others in the docs.  I'll definitely be willing to help on that front as I have some free time around Christmas.

**Comment by aharjula** [comment] 2016-11-17 07:28
Chris, the testers have not reported anything interesting yet but this does indeed seem to be a working design. 

As to `@stackunits(dispsf(a,4),cm)@` vs. `@dispsf(a,4)@ @cm@` it is all about consistent layout, especially the spacing between the number and unit parts. That second version doesn't really define it and what is worse if that second version is not placed inside a LaTeX math context it will generate two such contexts and should the line change between them it would look silly. The consistent layout thing is more about presenting same in the text as in the validation and other parts that the question author might not have too much control over. In addition to all that it helps that you can use that same logic in all the places where you have to ensure the correct presentation, including the question tests and model answer. But you could also say that it is a personal preference although I will probably add that to the Abacus guidelines at some point and after that there will be plenty of people expecting that. I'll leave the technical reasons I might have for wanting that a mystery, but lets just hint with "parsing" and "conversion"...

**Comment by sangwinc** [comment] 2016-11-17 09:23
Thanks Matti,

I think the example of @stackunits(dispsf(a,4),cm)@ vs. @dispsf(a,4)@ @cm@ really captures the difference between working at the CAS level (the first one) and working at the display level (the second one).  The stackunits function is a way of attaching units to numbers in a meaningful way.  The dispsf is to specify the numerical accuracy of a float (not just display it).  

I've always tried to work at the CAS level in the belief that, in the longer term, this would be the right thing to do.  We occasionally have to concatenate strings, but I've always seen this as a last resort if not an admission of failure!

**Comment by dhilsen** [comment] 2016-11-21 01:41
We tested the new code and also the attached question which Chris included above. I would first like to say that dispsf(a,b) is a wonderful addition, and with this addition we are able to accurately handle significant figures in all areas of STACK - calculations, answer tests, and text display! It has been truly remarkable to see all these developments take place with significant figures!

In our testing, dispsf(a,b) worked very well, however, we came across one issue with trailing zeros when testing values of 100 and 1000. Here's what we found:

dispsf(100,4) will display 100.00 (display should show 100.0)
dispsf(100,3) will display 100.0 (display should show 100)
dispsf(100,2) will display 100 (This display is correct)

dispsf(1000,4) will display 1000.0 (display should show 1000)
dispsf(1000,5) will display 1000.00 (display should show 1000.0)

dispsf(10,2) will display 10 (interestingly enough, this display is correct and does not follow the pattern above)

**Comment by aharjula** [comment] 2016-11-21 08:37
The problem here is probably around [this line](https://github.com/maths/moodle-qtype_stack/blob/ATUnitsNum/stack/maxima/assessment.mac#L290) it tends to assume that the value does not have an exact integer log_10 and as it does not handle that edge case it can't identify this situation... The thing works if you put 101 or 99 as the value there. Hopefully, Chris can type up a fix soon, maybe this should be checked for also in the old NumSigFigs test but as that exists no more it is not an issue. Apparently, this favourite example of mine did not get an test case then...

As to why it works for 10 and not for 100, maybe there are some floating point issues causing the log to give wrong values or some automatic more exact optimisations for common logs like ln(10), might require defining those to make cover these edge cases.

**Comment by sangwinc** [comment] 2016-11-21 10:18
Exactly Matti,

The minimal example is the difference between
dispsf(100.0000000000001,3);
(which displays correctly) and
dispsf(100.00000000000001,3);
which does not....

**Comment by aharjula** [comment] 2016-11-21 10:22
Hmm quick testing says that that `float()` causes issues, maybe eval with `,numer` instead?

**Comment by aharjula** [comment] 2016-11-21 10:31
Just for fun reference, newer trust floats or software doing stuff with them:
```
(%i27) floor(float(log(abs(100))/log(10)));
(%o27) 1
(%i28) floor(float(log(abs(100))/log(10))),numer;
(%o28) 2
```

**Comment by sangwinc** [comment] 2016-11-21 14:48
Well, I don't think we will ever cure all these problems, but printing 100 with the right (modest) number of significant figures should not fail!  I've used the bfloat routines here, which are more accurate.

**Comment by dhilsen** [comment] 2016-11-21 16:10
I can appreciate all the coding complexities that are involved in making dispsf(a,b) handle all situations. Attaining a level where it is able to handle the vast majority of situations is a noteworthy achievement!
 
Picking up on the discussion above regarding best practices to authoring a question, I was hoping to get some further clarification. In the past we've used the function significantfigures(a,b) wrapped around the mathematical expression which yields the solution to the question, and then placed this in the teacher answer field (TAns) and the model answer field. This was primarily done so that the correct answer would be displayed to the student with a reasonable number of significant figures. Now that we have a superior way to display the correct answer to the student using stackunits(dispsf(a,b),unit), my question is what is the recommended function that should be wrapped around the mathematical expression yielding the solution in the TAns field? For the most general case would we simply wrap the mathematical expression with float() so that it could be compared to the student answer in the PRT? 

(We are selective in our random variables such that the number of significant figures displayed to the student is also the same number used in the mathematical expression yielding the solution (with the exception of trailing zeros), so we don't seem to have the need to wrap the mathematical expression, or the random variables, in the significantfigures(a,b) function for the TAns field.)

**Comment by sangwinc** [comment] 2016-12-08 14:07
Yes David, I think the answer to this question is you use "float" to create a floating point number.

**Closed by sangwinc** 2016-12-08 14:07 UTC
