### ISSUE TITLE
SameType answer test stops giving "correct", "incorrect" or "partially correct" automatic feedback

### ISSUE THREAD

**Issue by smborio** [maths/moodle-qtype_stack#610] opened 2020-07-11 14:45 UTC
Hi,

When using the SameType answer test I'm not getting the usual message and green tic, red cross or yellow semicircle for correct, incorrect and partially correct responses. The scoring and test work perfectly fine but it's a shame if I can't have consistency in the type of automatic feedback. I can think of a couple of possible workarounds without using the answer test but it'd be a shame. I attached the (incomplete) question, I'm referring to PRT1 Nodes 5 and 6 (for example entering the correct answer without y=, or the answer 'y=x'.

Thanks!

S
[questions-eCampus-BCW4 - #8 parallel and perpendicular lines-20200711-1543.zip](https://github.com/maths/moodle-qtype_stack/files/4906935/questions-eCampus-BCW4.-.8.parallel.and.perpendicular.lines-20200711-1543.zip)

**Comment by sangwinc** [comment] 2020-07-13 16:20
Santiago, I've looked at your question.  If you add in some question tests (which are missing from your example!) you can see that in the case a student types in just "m*x+c" the code in the feedback variables throws a runtime error.  That, I think, is where your problems might start!

You need to add in a clause to the feedback variables

`mm:if equationp(ans1) then ... else ...`

anyway, I think this is a question authoring problem and not a bug with SameType so I'll close this issue!

**Closed by sangwinc** 2020-07-13 16:20 UTC
