### ISSUE TITLE
cartesian_product produces a lisp error

### ISSUE THREAD

**Issue by ReijoJaakkola** [maths/moodle-qtype_stack#759] opened 2021-11-23 18:02 UTC
I'm trying to form a cartesian product of two sets in a STACK exercise using the following command
`product: cartesian_product({2,3},{4,5})`
but I get the following lisp error:
`The value 4 is not of type LIST`
Since this works just fine on maxima, I have to assume that the issue is in STACK.

To the best of my knowledge, I'm using the newest (released) version of STACK.

**Comment by sangwinc** [comment] 2021-11-24 13:44
I'm sorry, I can't reproduce the error on https://stack-demo.maths.ed.ac.uk/demo/ or on my development machine.  Please email me off the list (at Edinburgh) and we can look more deeply at your particular set up.  Since I can't reproduce this issue I shall close it for now!

**Closed by sangwinc** 2021-11-24 13:44 UTC
