### ISSUE TITLE
Illegal string offset warning after upgrading to php 7.1.1

### ISSUE THREAD

**Issue by knedlyk** [maths/moodle-qtype_stack#266] opened 2017-01-25 10:45 UTC
After upgrading to php 7.1.1 stack (maxima) cannot evaluate mathematical expressions. Debugging shows that it caused by some incompatibilities with newer php version (7.1.1). It worked OK with php 7.0.1. Below some strings from stack healthcheck debugging:

Maxima version

Warning: Illegal string offset 'TimeStamp' in /srv/http/moodle/question/type/stack/stack/cas/connector.class.php on line 272

Warning: Illegal string offset 'Locals' in /srv/http/moodle/question/type/stack/stack/cas/connector.class.php on line 272

Warning: array_key_exists() expects parameter 2 to be array, string given in /srv/http/moodle/question/type/stack/stack/cas/connector.class.php on line 186

Warning: Illegal string offset 'PREPARSE' in /srv/http/moodle/question/type/stack/stack/cas/connector.class.php on line 277

Warning: Illegal string offset 'errors' in /srv/http/moodle/question/type/stack/stack/cas/connector.class.php on line 281

Warning: Invalid argument supplied for foreach() in /srv/http/moodle/question/type/stack/stack/cas/connector.class.php on line 196

CAS failed to return any evaluated expressions. Please check your connection with the CAS.

**Comment by aharjula** [comment] 2017-01-25 12:34
Thank you those warnings should not be. Should you wish to try a quick to remove those warnings in that connector.php file on lines 255, 256 change the empty string `''` to `array()` that might eliminate those warnings without breaking too many other things, but I am not so certain it would get your CAS to return stuff as those warnings are mainly caused by the CAS not returning stuff and not actually causing CAS to not return values.

I am not certain if we even support PHP 7.1 or have even defined what PHP versions we support so it might be that the simplest solution here would be to roll back on that version if at all possible, as I fear it might take some time for this to be resolved if the new PHP versions do something else that is causing unexpected behaviour.

To us devs: Why are there strings there that are being acted on as arrays? And how can they be there still after so many years of usage, nobody used this with more verbose logging levels or what? This is yet another thing that should be fixed once we get to go through the things Travis whines about.

**Comment by knedlyk** [comment] 2017-01-25 12:55
@aharjula Great, your simple workaround works! I replaced '' to array() on lines 255 and 256, it solves the issue with evaluating math expressions, but the warnings 
Warning: trim() expects parameter 1 to be string, array given in /srv/http/moodle/question/type/stack/stack/cas/connector.class.php on line 244
appear instead:

Uncached CAS call

This section always sends a genuine call to the CAS, regardless of the current cache settings. This is needed to ensure the connection to the CAS is really currently working.

Warning: trim() expects parameter 1 to be string, array given in /srv/http/moodle/question/type/stack/stack/cas/connector.class.php on line 244
......

You have chosen the "default" version of Maxima, so no Maxima version checking is being done. Your raw connection is actually using version "5.38.1". CAS returned data as expected. You have a live connection to the CAS.

**Comment by aharjula** [comment] 2017-01-25 13:03
Interesting, maybe I went too far... the line 256 one `$errors` should probably still be `''`.

Your quote there contains that ending that says that CAS responds and claims version 5.38.1, does the cas generate anything else on the page correctly? And have you cleared the cache?

**Comment by aharjula** [comment] 2017-01-25 13:12
Chris? What is happening [here](https://github.com/maths/moodle-qtype_stack/blob/master/stack/cas/connector.class.php#L270) and [here](https://github.com/maths/moodle-qtype_stack/blob/master/stack/cas/connector.class.php#L277) and how should [this](https://github.com/maths/moodle-qtype_stack/blob/master/stack/cas/connector.class.php#L197-L198) react to it?

**Comment by knedlyk** [comment] 2017-01-25 13:13
@aharjula  You are right, line 256 should remain unchanged, with `''`. Then all warning disappeared and healthcheck script is running without any warnings. Maxima evaluates all math, plot generates images. Sure, I always clear the cache before running healthcheck script.

**Comment by aharjula** [comment] 2017-01-25 13:17
Do those warnings come out from some debug feature of Moodles? And might it be that everything just broke down due to warnings getting displayed? As those original warnings should not have blocked the evaluation at all. Have you by any chance upped the verbosity of Moodles error reporting?

**Comment by knedlyk** [comment] 2017-01-25 13:20
@aharjula Yes, I enabled debugging in stack and in moodle, because after upgrading to a newer version of php, and I started to discover this issue.

**Comment by aharjula** [comment] 2017-01-25 13:23
Ok. So we now know that line 255 need some attention just to stop spamming those warnings and especially because those warnings cause trouble when in debug mode. Thank you for testing and reporting.

**Comment by knedlyk** [comment] 2017-01-25 13:23
@aharjula Without your workaround the healthcheck script ddoesn't evaluate math expressions neither images from plot.

**Comment by aharjula** [comment] 2017-01-25 13:25
Ok. Then we can probably assume that something in PHP 7.1 reacts very differently to those warnings than in earlier ones.

**Comment by knedlyk** [comment] 2017-01-25 13:26
It is for sure.

**Comment by sangwinc** [comment] 2017-01-25 13:52
Sorry I'm late to the party here. Thanks for reporting.

**Comment by aharjula** [comment] 2017-01-25 14:12
Well, you can at least make sure that connector.php line 255 gets fixed... And maybe try running STACK with more warning logging (to file instead of through Moodle) to see if this problem pattern appears elsewhere. New users will surely try new PHP versions so this might repeat itself in the near future.

**Comment by knedlyk** [comment] 2017-01-25 14:35
If something happened I'll report here.

**Comment by sangwinc** [comment] 2017-02-07 11:18
Did you fix this issue, and if so could you please send me a pull request so we can check this out and merge into master?

**Comment by aharjula** [comment] 2017-02-07 11:24
As said in the text above just change the connector.php line 255 to initialise an array instead of a string as accessing that string like an array is not tolerated by fresher PHP-versions. And should not be done in older ones either. I have not tested this myself but static code analysis (i.e. I looked at the code) says this is the way to go.

**Closed** 2017-02-08 12:45 UTC
