### ISSUE TITLE
More than few questions and totally broken

### ISSUE THREAD

**Issue by jval** [maths/moodle-qtype_stack#666] opened 2020-12-16 10:12 UTC
We use local maxima. After updating to the Moodle STACK plugin 4.3.7 and 4.3.8 all activities with more than a few questions just hang. I can see a lot of maxima processes taking all the resources. They just run and run. Nothing happens, except load increases so much other usage suffers too.

I have tried to downgrade but it's been made very difficult, for some reason I get "unknown platform linux" then. Downgrading only the plugin code or only stack/maxima was possible but those did not help.

**Comment by jval** [comment] 2020-12-16 10:14
I'm starting to wonder if there's a compatibility issue. This might have started when we upgraded Moodle to 3.9.

**Comment by sangwinc** [comment] 2020-12-16 10:31
Ok, I suggest you go back to the healthcheck page and check all your settings very carefully.  Email me privately at Edinburgh and I will help.  I suspect you need to re-create the Maxima image for the new version.

**Comment by timhunt** [comment] 2020-12-16 11:00
Where did you upgrade from? STACK >=4.3 is mcuh slower that STACK <4.3.

Moodle 3.9 should be better than earlier versions for STACK, because https://tracker.moodle.org/browse/MDL-67183.

**Comment by jval** [comment] 2020-12-16 11:01
The healthcheck page seems to report everything being ok. I have removed maxima* from the moodledata/stack directory and new image has been created.

I have also downgraded all the way back to 4.3.1 but no luck.

The thing is a question on its own works, the healthcheck page works (AFAIK), but when a quiz with a lot of questions is opened nothing happens, a white page eventually. And load increases etc.

**Comment by jval** [comment] 2020-12-16 11:17
I even tried 4.2.2 but the same happens with that version too. And yes, I removed maxima* so it created the maxima image. And healthcheck page was ok. There hasn't been a maxima OS package update in the recent past, so Moodle upgrade might have something to do with this. Though, it's the maxima command which runs and runs, so I'm not sure if Moodle can affect that or not.

**Comment by timhunt** [comment] 2020-12-16 11:20
Have you considered using https://github.com/maths/stack_util_maximapool ?

**Comment by jval** [comment] 2020-12-16 11:31
I have, and thanks for the reminder. However, the problem is not maxima being slow, it's maxima just running and running (looping or something like that) and eventually timing out.

Anyone using Moodle 3.9 and the default local maxima command (platform unix/linux), and having quizzes with a lot of questions working?

Could there be something with Moodle 3.9 and the way it handles the local maxima command? Quizzes with many questions probably execute maxima many times during the page load? Maybe 3.9 doesn't handle that situation any more for some reason..?

**Comment by aharjula** [comment] 2020-12-16 11:31
Bringing in the Pool might not help here at all, first, we have to figure out what is actually happening. Though, it would shift the load to another server and thus make the Moodle servers life simpler.

First of all when you say "a quiz with a lot of questions" what exactly does "lot" mean here? If all the questions need to be initialised from scratch as the caches are empty this can take longer than whatever PHP timeouts one has, if one has excessive numbers of questions or they are very complex ones. My opinion is that a lot for STACK, in general, is 10+ questions but one may need to tune that value for the environment and the questions.

You are saying that Maxima processes get stuck, do you have any idea from which questions those processes start and if they are due to the questions own CAS-initialisation or due to student inputs triggering expensive operations? You might want to look at [this](https://docs.stack-assessment.org/en/CAS/Optimising_Maxima/#terminating-runaway-lisps) to deal with this symptom even if the root cause is unknown. One must always remember that STACK does not estimate the complexity of the tasks it has been given and that some tasks can easily be too complex to evaluate in a sensible time and some may lead to infinite tasks etc.

Overall if you did not have trouble with 4.3.1 this is unlikely to be a problem with the large mods in 4.3 itself but something else is now broken.

Just to make it clear, you have ensured that the maxima-image is fresh by destroying the file from the filesystem and then recreating it through the health check page, we can probably assume that when you have been at that page you have also cleared the cache there. You might also want to try purging Moodle caches as you have been doing quite a lot of version changes...

**Comment by jval** [comment] 2020-12-16 11:36
The teacher has told me it's roughly 25 to 35 questions and then it breaks. I'll test with a longer PHP max_execution_time.

**Comment by aharjula** [comment] 2020-12-16 11:42
Well, that is a lot of questions, each question calls maxima multiple times for the initialisation of the quiz and Moodle repeats that for each quiz load + then the grading. In addition to that, the parsing changes that 4.3 made might slow things down more if those questions have very long question-variables and people have not used semi-colons to terminate their statements and STACK needs to guess the correct splits, that could easily timeout things if one has that many questions.

More than likely the teacher should split that quiz to parts. Though with MaximaPool and reasonable deployed-variants sets one can stretch to 25-30 if the questions are not too complex (especially the randomisation logic).

**Comment by jval** [comment] 2020-12-16 11:47
Solved! Big thanks guys!

And sorry for this. I was told it just broke out of the blue but this must have been about teachers adding more questions than before. The quiz I checked and tested with takes just a few seconds longer than the previous max_execution_time to load when cache is empty.

**Comment by aharjula** [comment] 2020-12-16 11:54
Thank you for the number 25-30, it gives us some context. Hopefully, the changes planned for STACK 4.4 will up that number quite a lot. Though I assume that 4.5 is the point where our internal reworking starts to truly pay off. 

Could you state the earlier max_execution_time for completeness sake?

**Comment by jval** [comment] 2020-12-16 11:56
Strange. When I closed the preview by starting a new one suddenly it loads and loads again. Not very logical to me... Although the preview was open before I did clear the STACK's cache between tests. The max_execution_time was the default 30.

**Comment by jval** [comment] 2020-12-16 12:12
It did work but took a really long time this time. Btw. are the results cache per user or per course/quiz/question?

**Comment by aharjula** [comment] 2020-12-16 12:16
The CAS evaluation is cached at the system level, executing equivalent questions with the same seeds will find their results from the cache. Of course, cache misses will be common if the questions do not use so-called [deployed variants](https://docs.stack-assessment.org/en/Authoring/Deploying/) as then cache misses will happen due to seeds into matching.

Currently, however, only the CAS evaluation is cached and much of the other question initialisation logic is not so it will be expensive to open a quiz with that many questions no matter what...

**Comment by jval** [comment] 2021-01-22 09:34
Teachers tell me everything is slower than before but for some reason going back to older STACK version did not help. So now I tried to set up maximapool with Tomcat 9 and OpenJDK 11 but "1+1;" timeouts, and low level check gives:

Executing command-line: /var/lib/maximapool/2020120600/maxima-optimised

Waiting for target text: 'Maxima restarted.'

Timeout!

**Comment by jval** [comment] 2021-01-22 09:35
And btw. when I created the optimised image there were some warnings. You are probably aware of those though.

**Comment by jval** [comment] 2021-01-22 09:40
The warnings, when loading maximalocal.mac in Maxima:

define: warning: redefining the built-in function intervalp
warning: variable simp (declared type boolean) assigned type any.
define: warning: redefining the built-in function texnumformat
warning: encountered undefined variable stackintfmt in translation.

**Comment by aharjula** [comment] 2021-01-22 09:46
And you are sure that this is the correct file for that version and the MaximaPool running system can execute it `/var/lib/maximapool/2020120600/maxima-optimised`, if it is a file from some backup and you have updated something else then it might not even execute. The error is pretty obvious it did try to execute but did not see the expected output, either it did not receive any output or the output is different if the latter then tune the expectations in the configuration. So try executing that on the server (ideally as Tomcat and in the environment Tomcat executes stuff) and see what happens.

And the warnings are natural just to let people know that certain things are being redefined, those do not matter.

Overall people jumping back in versions tend to get versions mixed so the first step is always to check that one has the correct versions in use and the simplest way to do that on the MaximaPool side is to copy the scripts from the Moodle side and build the images from scratch. Also is 2020120600 the version STACK expects, do you have multiple versions in that pool... 2020120600 is a post 4.3 version and if your STACK is pre 4.3 they do not even "speak the same language".

**Comment by jval** [comment] 2021-01-22 09:54
I'm setting up MaximaPool in a new separate server so there are no other versions or previous installations there. I've now also changed the Moodle server's local maxima to optimised and health check page reported optimised is in use and everything is OK. (But slow. But that just shows the optimised image there seems to be working, and I created the optimised image in the MaximaPool server the same way without errors.)

**Comment by jval** [comment] 2021-01-22 09:55
What is the correct command to test the optimised image from the command line? Thanks.

**Comment by aharjula** [comment] 2021-01-22 09:57
"Executing command-line: /var/lib/maximapool/2020120600/maxima-optimised" as MaximaPool stated.

**Comment by jval** [comment] 2021-01-22 10:00
Not sure if the parameters should be part of the command in process.conf or not. But does not work that way either:

Executing command-line: /var/lib/maximapool/2020120600/maxima-optimised -eval '(cl-user::run)'

Waiting for target text: 'Maxima restarted.'

Timeout!

**Comment by jval** [comment] 2021-01-22 10:01
/var/lib/maximapool/2020120600/maxima-optimised can be executed but doing so does not print anything. It just runs quickly, no output. Not sure what that means.

**Comment by jval** [comment] 2021-01-22 10:06
Sorry, the health check is NOT ok with the optimised image. The end of the page does state OK twice but there are e.g. no plots now.

**Comment by aharjula** [comment] 2021-01-22 10:07
The parameters definitely need to be part of the process conf if they are part of the way things are executed. Should not typically be for images of that form. MaximaPool does not add parameters as it has no idea about what to add.

If it does not output anything then it is not a valid image, a valid image starts and waits for input. Are you sure you built that image in the MaximaPool server, transferring images between machines tends to fail due to differences between the versions of installed libraries on those machines.

Note that depending of what lisp is in use the command line for executing images can vary, some lisps like SBCL generate binary images that are directly executable while others generate just memory states that are given as parameters to lisp interpreters.

Always clear the cache when doing version changes.

**Comment by jval** [comment] 2021-01-22 10:07
If I go with the default image, I'm unsure what is then the correct value in process.conf. Does the eval part belong there or not..?

**Comment by jval** [comment] 2021-01-22 10:09
Yes I built the MaximaPool's optimised maxima image on that server, and the Moodle's one on that server.

**Comment by jval** [comment] 2021-01-22 10:10
I used GCL. maxima --list-avail output from both machines:

Available versions:
version 5.42.1, lisp gcl

Available versions:
version 5.42.1, lisp gcl

**Comment by aharjula** [comment] 2021-01-22 10:12
What is a default image? What eval-part, as I stated what belongs there depends entirely on the type of image you are working and that depends on the type of LISP...

If it is GCL then the eval argument is part of the command for executing an image.

**Comment by jval** [comment] 2021-01-22 10:14
From MaximaPool machine, running exactly what is in process.conf as command.line:

# /var/lib/maximapool/2020120600/maxima-optimised -eval '(cl-user::run)'
Warning: argument a not recognized.
Maxima restarted.
(%i2) quit();

**Comment by jval** [comment] 2021-01-22 10:16
Since that setting value does run maxima, I restarted tomcat9 and tried again the low level test. But no:

Executing command-line: /var/lib/maximapool/2020120600/maxima-optimised -eval '(cl-user::run)'

Waiting for target text: 'Maxima restarted.'

Timeout!

**Comment by aharjula** [comment] 2021-01-22 10:25
What comes to mind is whether those quotes in that argument go through the processing in the correct way. Maybe try without them or with double-quotes in the config. I have not seen GCL imaged MaximaPools in action so I don't actually know the format to input that command line.

**Comment by jval** [comment] 2021-01-22 10:30
Removed quotes, now:

Executing command-line: /var/lib/maximapool/2020120600/maxima-optimised -eval (cl-user::run)

Waiting for target text: 'Maxima restarted.'

Warning: argument a not recognized.

Maxima restarted.

Sending command:

load("/var/lib/maximapool/2020120600/maximalocal.mac");

Waiting for target text: '"/var/lib/maximapool/2020120600/maximalocal.mac"'

(%i2) 

[ STACK-Maxima started, library version stackmaximaversion ] 

(%o2)           /var/lib/maximapool/2020120600/maximalocal.mac
(%i3) 

Timeout!

**Comment by jval** [comment] 2021-01-22 10:31
High level now gives java.lang.RuntimeException: Process timed out.

**Comment by jval** [comment] 2021-01-22 10:34
Duoble quotes just timeouts. Maybe without quotes is correct, but there is still something wrong anyhow.

**Comment by jval** [comment] 2021-01-22 10:37
The image is probably OK. From command line:

# /var/lib/maximapool/2020120600/maxima-optimised -eval '(cl-user::run)'
Warning: argument a not recognized.
Maxima restarted.
(%i2) 1+1;
(%o2)                                  2
(%i3) quit();

**Comment by jval** [comment] 2021-01-22 11:03
I'm not sure if the timeout from low level test is even an error since nothing is given there. But high level and that "1+1;" timeouts might be because nothing is transmitted to maxima... So something wrong with the way the servlet is configured, or even a bug in the recent version?

**Comment by jval** [comment] 2021-01-22 11:09
The Moodle's optimised image is OK. I just had to clear the cache to get the plots to show on the healh check page.

**Comment by aharjula** [comment] 2021-01-22 11:12
One thing that looks odd is that "[ STACK-Maxima started, library version stackmaximaversion ]" output. Why has it not added the correct version there? Seems to me like the image does not contain the libraries and therefore the value is missing. Remember that when generating the image one needs to have those load statements in the maximalocal.mac, and if one loads a maximalocal.mac over an image after generation then it must not load things. One does not need to load it over a proper image, of course not loading means that the process.conf needs to be adjusted accordingly, and I won't be explaining that here.

**Comment by jval** [comment] 2021-01-22 11:35
Thanks! Looks promising now.


Low level:

Executing command-line: /var/lib/maximapool/2020120600/maxima-optimised -eval (cl-user::run)

Waiting for target text: 'Maxima restarted.'

Warning: argument a not recognized.

Maxima restarted.

Sending command:

load("/var/lib/maximapool/2020120600/maximalocal.mac");

Waiting for target text: '"/var/lib/maximapool/2020120600/maximalocal.mac"'

(%i2) 

[ STACK-Maxima started, library version 2020120600 ] 
(%o2) "/var/lib/maximapool/2020120600/maximalocal.mac"

Start-up time: 371 ms

Sending command:

1+1;
concat("--COMPLETED--k","ill--PROCESS--");

Waiting for target text: '--COMPLETED--kill--PROCESS--'

(%i3) 

(%o3) 2
(%i4) 

(%o4) "--COMPLETED--kill--PROCESS--"
(%i5) 

Sending command:

quit();

Total time: 378 ms


High level:

Warning: argument a not recognized.
Maxima restarted.
(%i2) 
[ STACK-Maxima started, library version 2020120600 ] 
(%o2) "/var/lib/maximapool/2020120600/maximalocal.mac"
(%i3) 

Sending command: '1+1;'.

(%o6) 2
(%i7) 
(%o7) 

Time taken: 375 ms


And the "1+1;":

Warning: argument a not recognized.
Maxima restarted.
(%i2) 
[ STACK-Maxima started, library version 2020120600 ] 
(%o2) "/var/lib/maximapool/2020120600/maximalocal.mac"
(%i3) 
(%o6) 2
(%o7)

**Comment by jval** [comment] 2021-01-22 11:38
Have I understood it correctly that the installation instructions of MaximaPool are for running it on the same server as Moodle? Plots are normally just stored locally and Moodle reads that directory? Now, if I want to use a separate MaximaPool server, the plots need to be sent to Moodle too. And the instructions mention something about configuring the servlet to run in server mode, but how? There are no instructions for how to actually do that. Which setting it is, in which conf file? Thanks!

**Comment by jval** [comment] 2021-01-22 11:41
Maybe set "file.handling = false" in process.conf?

**Comment by aharjula** [comment] 2021-01-22 11:44
The current MaximaPool of the default multiple-pools branch by default transfer the files and is very much intended to be executed on a separate server or a pool of servers.

**Comment by aharjula** [comment] 2021-01-22 11:45
You have to go very far in MaximaPools history for the operating mode where it wrote plots to Moodles directories and I know of no one that still does that. But it is still an option that one could use in convoluted conditions.

**Comment by jval** [comment] 2021-01-22 11:53
Okay, it looks like the "Server" mode in Moodle does the right thing. I changed to that and gave the URL of the MaximaPool. Cleared the cache and ran the Moodle STACK health check page. It says I'm using server, plots show and it prints OK. So, looks good.

I'll test the actual teaching materials next. Let's see if I still get a timeout or if it works now...

**Comment by jval** [comment] 2021-01-22 11:59
It still takes forever. Are others running Moodle 3.9 and the latest stable STACK? Or is this something with Maxima actually since now the forever running maxima processes are on the MaximaPool server..? The Maxima version:

# maxima --version
Maxima 5.42.1

We are using Debian stable: Debian GNU/Linux 10 (buster)
The exact version of maxima package: 5.42.1-1
And it's amd64.

**Comment by aharjula** [comment] 2021-01-22 12:09
![Screenshot_2021-01-22_14-06-54](https://user-images.githubusercontent.com/980957/105488933-1c65b780-5cbb-11eb-820f-8eab4d88bac3.png)

That is from a MaximaPool backing up the newest STACK and Moodle 3.9. It works just fine. Hows your numbers there? That runs on SBCL backed Maxima. That load there, the frequency, comes from clearing the cache and running the answer-test test suite.

**Comment by jval** [comment] 2021-01-22 12:15
First, I want to tell you that the material I tested and which timed out does eventually finish but it requires a long time. Lifting timeout limit from 120 to 300 helped. But that is of course not OK for us. I just wanted to tell that because it shows Maxima does eventually calculate, the problem is the weird extremely slow performance.

**Comment by jval** [comment] 2021-01-22 12:17
Pool performance - 2020120600
Name	Value
Ready processes in the pool:	51
Total processes started:	631
Current demand estimate:	0.00870631172775015 Hz
Current start-up time estimate:	319 ms
Recent start-up times:	275 ms 348 ms 319 ms 322 ms 331 ms 323 ms
Recent request times:	14:06:52 14:06:52 14:06:53 14:06:56 14:06:57

**Comment by jval** [comment] 2021-01-22 12:29
What about the Maxima side of things? Should it really be just about installing the "maxima" Debian package, which I have done? No additional libraries needed etc? Anything you have done differently?

**Comment by jval** [comment] 2021-01-22 12:34
And what about Maxima version? I'm wondering could this be related to that because I have upgraded from 5.38.1 to 5.42.1 in the summer.

**Comment by aharjula** [comment] 2021-01-22 12:35
Well, those startup times do not look good, if you have images then it should start in < 50ms even from spinning rust. Assuming that this is not an IO-problem you really should throw that GCL Maxima away and try some other LISP SBCL or CLISP tend to work just fine. Seems more like a CPU or memory limitation though as the request times are so spread out, though that is not from an active situation so who knows. A single Moodle user pushing the answer-test test-suite should be able to get the frequency up to 20-40 and the input-tests set can generate even higher bursts as it has way less to evaluate on the Moodle side.

Overall, I really dislike it when people throw the word "slow" around without context. There are two very important details when talking about "slow", one is what you are doing, which was what we had at the start of this issue i.e. do not expect fast responses when dumping multiple times the normal amount of questions to be processed at the same time and the second one is the scale of the operation and the resources given for processing stuff, if you are running this on a "celeron" with megabytes of RAM and expecting hundreds of concurrent users then things will obviously not be fast. You really need to define the key performance details of the servers in play and the number of users expected for anyone to even start trying to understand what is happening or how "slow" it will be.

Maxima from packages works for some for others not so much, you obviously also need gnuplot for plotting. Most people though do not like the version coming from the packages and compile their own Maxima installations with whatever LISP they like. I personally hate the GCL LISP present on debians as it limits the argument count of functions, SBCL seems to be quite popular.

My numbers were from 5.42.1 so no it has not gotten slower there.

**Comment by jval** [comment] 2021-01-22 12:43
Well, I downgraded maxima to 5.38.1 but no, still slow. So if it's something related to a dependency, maxima itself is not it. This could be something else related to differences between Debian 9 and 10.

**Comment by jval** [comment] 2021-01-22 13:43
How fast CPU is recommended, what about the amount of RAM? Thanks.

**Comment by jval** [comment] 2021-01-22 13:58
Well, this does not seem to be related to CPU and/or RAM. Tested with a lot more, no effect.

Different lisps apparently require rebuilding maxima, if I have understood correctly.

**Comment by jval** [comment] 2021-01-22 14:02
Shouldn't be an IO issue since I have now tested on different hardware.

**Comment by aharjula** [comment] 2021-01-22 14:18
If you think it's about the speed of the CPU or just about RAM you will never have a fast enough one nor enough RAM. Please describe the relevant context before asking such details.

Do not use any numbers below in any way, these are opinions valid at this very second on assumptions I make in my context and do not apply on all cases:
 1. For Moodle One CPU-core or about 1-1.5 hyperthreads per 15 distinct users in a 15 minute interval.
 2. For Moodle minimum of 2GB RAM for each thread, preferably 4.
 3. For MaximaPool 4-6 threads and 8GB for up to 100 distinct STACK users in 15 minute interval. When selecting the number of ready processes to keep active aim for about half the memory or less, to allow the processes room to do large things.
 4. If more users add more MaximaPool nodes don't grow the nodes themselves, put a load balancer in front of them.
 5. Note that in large Moodles you will not have sensible machines that can fit all the cores or RAM and will need to cluster stuff and that is a completely different problem.
 6. You will need a separate database server to offload complex load an IO from the Moodle server(s). In large use, it better be clustered and replicating on multiple nodes.
 
 As to speed median speeds of Xeon or EPYC processors of recent generations are enough, this is not high-frequency trading, more nodes means more IO and one must pay much more attention on the network capacity between all the nodes once the scale grows.

In any case, your problem is probably debian GCL Maxima. Just try these three statements in it:
```
ratprint:false;
showtime:true;
m:invert(apply(matrix, makelist(makelist(ev(sin(x*y),numer),x,1,15),y,1,15)))$
```
Just for comparison, the ubuntu GCL version on 20.04 times at 4.31s on my machine while custom SBCL compiled one gets that done in 0.14s, so basic software failures can be significant things. Obviously matrix inversion is not the feature that is the fairest comparison...

**Comment by jval** [comment] 2021-01-22 15:36
I'm now running maxima-clisp packaged by Maxima. I have created an optimised image. Direct command line usage of the same command as in process.conf works. No errors and "1+1;" works.

The teaching materials still load and load. It eventually works, but this change did not help either. Here are the performance figures from the servlet:

Pool performance - 2020120600
Name	Value
Ready processes in the pool:	52
Total processes started:	282
Current demand estimate:	0.022952098969450756 Hz
Current start-up time estimate:	267 ms
Recent start-up times:	292 ms 154 ms 363 ms 338 ms 190 ms
Recent request times:	17:26:00 17:26:02 17:29:26 17:29:26 17:29:28

**Comment by jval** [comment] 2021-01-22 15:42
Tried that with the current clisp version:
Evaluation took 0.7558 seconds (0.7559 elapsed) using 12.064 MB.

**Comment by jval** [comment] 2021-01-22 16:11
Now using sbcl:
Evaluation took 0.4760 seconds (0.4760 elapsed) using 27.072 MB.

**Comment by aharjula** [comment] 2021-01-22 16:32
I really see very little point in these constant mails about some random numbers (those are the CLI numbers, wonder if your tomcat is bad and adds way more during the HTTP processing), I assume that the original GCL number was larger and if so you are getting smaller numbers that still are bigger than my stated number. Surely, that difference should point out to the obvious fact that your machine is somehow slow compared to mine (obviously I won't divulge the specs of mine as that would provide much-needed context). Though now that Maxima seems to be closer to reasonable maybe it is the Moodle machine that is slow or has some wrong software setup. Maybe go ask the Moodle people about tuning PHP installations to fix that, they might know if your flavour of debian has some insane combination of libraries, or maybe you would tell them if your context includes some other component that you have added that has made things slow, or maybe you would tell them the specs of the machine so that they could tell if there is any hope for things to be fast.

In any case, nice numbers showing that one may need to trade memory for speed, again something that depends on your context.

**Comment by jval** [comment] 2021-01-22 16:36
I haven't timed the quiz load exactly, and it is pointless anyway since it uses different values every time. But it might be a tiny bit faster with sbcl. Or not. Anyway, it takes like three to over four minutes to load anyway. It has been like that all the time, so no real difference.

I know it is always a bit slow when there are many questions in the same quiz. But I'm wondering can it be that slow... Is this normal. :)

Btw. is there a need to tune the MaximaPool configuration (pool.conf)? I'm using defaults.

**Comment by jval** [comment] 2021-01-22 16:40
Performance data from MaximaPool now that running with sbcl:

Pool performance - 2020120600
Name	Value
Ready processes in the pool:	54
Total processes started:	727
Current demand estimate:	0.10682391146434218 Hz
Current start-up time estimate:	131 ms
Recent start-up times:	143 ms 144 ms 145 ms 136 ms 87 ms
Recent request times:	18:39:21 18:39:57 18:40:00 18:40:00 18:40:01

**Comment by aharjula** [comment] 2021-01-22 16:49
I don't know, is it necessary to answer any questions to get some help? Who knows? "THE QUIZ" wonder what that is surely it is some universally know constant quiz running on some universally known constant machine so that we know when it is slow and when it is fast, seriously if you expect everything to be given and solved for you you need to give some context... On the other hand, I have a company that will happily keep answering things at 300€/h no matter how incomplete the questions are.

Maybe you'll manage to write some proper context and answer the questions I have written in this thread, and maybe I'll get back to this at some point in a week or so but currently, I need to cool down.

**Comment by jval** [comment] 2021-01-22 17:11
Big thanks for the help given today!

I tried to lift up the numbers in pool.conf. Three minutes this time... All these tunings do help marginally it seems but there's no big improvement like I hoped.

I asked the teacher to send the Moodle quiz to you, if you can e.g. test it in your Moodle and see how long it takes to load the preview.

We are happy to use some euros if that helps. :) But you can discuss that with the teacher if he sends the material to you.

Again, I'm really grateful for the help! Thank you!

**Comment by jval** [comment] 2021-01-22 18:57
The teacher's Moodle quiz I'm using for testing causes MaximaPool to start 291 new processes. Unless I'm mistaken that means it calls maxima that many times.

How is the teacher's code parsed and handled in Moodle's qtype_stack: each row causes a separate cas call? :)

**Closed** 2023-07-20 16:08 UTC
