### ISSUE TITLE
\{ in Question Text mathmode disrupts HTML markup

### ISSUE THREAD

**Issue by chigle** [maths/moodle-qtype_stack#1246] opened 2024-08-12 14:36 UTC
Apologies for a possible duplicate report or if this has already been fixed in the current version. 

STACK ver. 4.6.0 seems to break the previously working syntax (tested in ver. 4.4.6):

`\{` in mathmode disrupts the HTML markup (such as in a table: `<td>\(...=\Bigl\{...\)<td/>` ). Changing this to `...=\Bigl\{\vphantom{\}}...` fixes that.

Many thanks!

**Comment by sangwinc** [comment] 2024-08-13 05:50
Sorry you're having problems.  This kind of thing is tedious!

Here is my example
````
<table><tr>
<td>\(f(x) =\Bigl\{ \begin{array}{ll} x^2, & x\geq 0 \\ -x^2, & x <0 \end{array}\)</td>
</tr></table>
````
It works just fine on https://stack-demo.maths.ed.ac.uk/demo/

To what extent is this problem actually to do with qtype_stack (the question type) rather than an interaction between moodle, MathJax and a particular browser?  Does your example break outside a STACK question?  If so, I'm not sure why this is a bug with the STACK plugin itself?  For that reason I'll close this issue.  If STACK, and only STACK, is _creating_ this problem please reopen it with a more specific way to reproduce the error within STACK itself.

Sorry to pass you on here!  Please let us know if you find out the cause, as other users might find that useful.

Chris

**Comment by chigle** [comment] 2024-08-13 22:17
Thank you for your prompt reply.  You are correct - it seems the **Moodle**  is the culprit, not the STACK qtype_stack issue. It has been reproduced in Chrome and Firefox. 
Version details: Moodle 4.1.11+ (Build: 20240802); STACK question 4.6.0; (Build: 2024060300)

Steps to reproduce:
1. Create a Moodle question (e.g. True/False or STACK)
2. Enter the table-formatted expression in the question text editor (in the HTML mode):
```
<table><tbody><tr>
    <td>\( f(x)=\Bigl\{ \)</td>
     <td> \( \begin{array}{ll} x^2, &amp; x \geq 0 \\ -x^2, &amp; x \le 0 \end{array} \)</td>
</tr></tbody></table>
```

3. Save and preview. The output will be something like  "`f(x)={ </td> <td> ...`".

**Comment by sangwinc** [comment] 2024-08-14 03:19
Since this problem is in any Moodle question (not specifically qtype_stack), it is either your local setup or a problem with the Moodle filter.  I think you should raise this on the Moodle forum.  https://tracker.moodle.org/

I can't reproduce the problem, and so I'll close this issue as "not a STACK" problem. I'm sorry I can't offer to help further this time.

Chris

**Closed by sangwinc** 2024-08-14 03:19 UTC
