### ISSUE TITLE
String Tests

### ISSUE THREAD

**Issue by nfa019** [maths/moodle-qtype_stack#549] opened 2020-01-29 13:51 UTC
I read in the documentation under the table with the string tests

"NOTE: we plan to remove this test in STACK version 4.3. Do not use this test."

Do you plan to skip all String tests or just the Regex tests? 
I would like to use Regex tests for problems from theoretical computer science, so this would be rather sad.
Is there planned any substitute for this ?

**Comment by aharjula** [comment] 2020-01-29 14:20
#512 in short this is preparation for a future move that probably leads to regexp-syntax changing, should someone know of a functioning Maxima side regexp implementation with PCRE-syntax that would work as a drop-in replacement for the current PHP-side test then there would be no period when STACK has no regexp-test.


The reason why regexp is being removed is that we aim to move the whole PRT-evaluation to the CAS. Doing it in pieces because one particular test requires PHP-side evaluation is not something we  want to do, and the regexp test is currently the only test we have that requires us to split the evaluation.

We do acknowledge that a regexp test is something we should have and aim to return it at some point but it needs to be such that it is evaluated on the CAS side. The problem is that we know of no Maxima implementation of regexps that would use the same syntax as the PCRE one on the PHP-side and as the migration from one syntax to another is not a simple task particularly if the other one does not support the same patterns it was thought better to remove the test for now and return it once possible.

One of the reasons why the migration is especially difficult is that in the user-base we know the test has not been used and therefore we have no idea what forms of patterns people have used and cannot in any way estimate the work related to migrating existing patterns to a new syntax. Having checked your repositories you seem to be converting some existing problems from some other system to STACK, what regexp-syntax does that use, are you already doing conversions between regexps?


For those wishing to do regexp testing in the interim era I recommend finding out which Maxima-library best suits your use-case and simply loading it into you STACK installation and using it directly. By directly I mean evaluating the logic of your test in the feedback-variables to generate a boolean value and then using that boolean in the PRT to decide which branch to follow.

The String-test should be safe but even for that use-case I would recommend writing the testing logic by hand using Maxima side functions, just in case.

**Comment by nfa019** [comment] 2020-01-29 14:36
To check some strings against regexes, we use Perl in the LON-CAPA problems, so it is the Perl Regex Syntax. These kind of problems cannot be converted completely automatically, so there will be some work to be done by hand anyway. The regexes used here are not too complicated, so may be they are equal in most dialects. (For checking things like: given this regular language/grammar / finite automaton, give me some words of the language)

**Comment by timhunt** [comment] 2020-01-29 14:40
If you want questions graded with regexp, then really stack is the wrong tool for the job.

You might like to look at https://moodle.org/plugins/qtype_coderunner or https://moodle.org/plugins/qtype_regexp.

**Comment by nfa019** [comment] 2020-01-29 14:45
I will have a look, but my questions usually are randomized ...

**Comment by aharjula** [comment] 2020-01-29 15:09
@timhunt  Always remember that there is a reason why people do not want to use the single-hit wonder question-types. It might not be that there is randomisation it might simply be the the logical second part of the question need some other feature. Or it could be because they use STACK for everything else and would want to use it for this too, in that case we might point to some other direction. But by default if someone ends up on the STACK issues side we should probably assume that they have a reason, beyond the specific issue, before saying that STACK is wrong.

**Comment by aharjula** [comment] 2020-01-29 15:17
@nfa019 if you could look into [pregexp](https://github.com/ds26gte/pregexp/) or the related sregexp that come with a recent Maxima install and test if your patterns work on them it would be of great help. Those are the currently know implementations, but surely more exist, our primary requirement for them would be the support for UTF-8.

**Comment by nfa019** [comment] 2020-01-29 15:24
@aharjula Thank you, I will have a look at those and test. At the moment, I only have math courses, so I don't need it immediately.
Best wishes
Frauke

**Comment by nfa019** [comment] 2020-01-29 16:14
I have a Maxima 5.41.0 on my notebook, is this OK for testing ?

**Comment by aharjula** [comment] 2020-01-29 16:29
Should be, running e.g. `load("sregex");` should quite fast tell you if it has that library. As to documentation about what to do after that, that might be bit more difficult. For pregexp there is documentation but as its for LISP then using it directly may be a bit cumbersome, sregxep is apparently a wrapper easing the use in Maxima. I trust you can find some examples about its functions and their use.

In general the library whatever it ends up being should work for Maximas from version 5.38 upwards, but that is something I can deal with once some form of candidate solution has been identified.

**Comment by sangwinc** [comment] 2020-01-29 17:08
Sorry I'm late to the party here.

Can I ask you to post some examples of students' expressions and what you are trying to establish.  There have been lots of cases where there was already a way to do this in STACK (!) or, it is a very sensible mathematical property we can and should support.

The whole point of STACK is to establish mathematical properties of expressions.  It would have been easier to compromise earlier in the design, but I'm glad we have stuck to this principal.  E.g. look at the "equality up to commutativity and associativity" test, or the "factored form" test.

I'd much rather understand the maths you are trying to assess, and see if we can support that is a genuine and meaningful way.

**Comment by nfa019** [comment] 2020-01-30 11:04
this is a simple example of an problem I would have used the String/regex test in Stack for (this not maxima but Perl from the old problem:

// Start script in Perl
---------------------------------------------
$r1 = random(0,3,1);
$r2 = random(0,4,1);
@variables=random_permutation($r1,('T','U','V','S'));
@terminals=random_permutation($r2,('a','b','c','d'));
$S = $variables[1];
$T = $variables[2];
$t1=$terminals[1];
$t2=$terminals[2];
@productions = ("$t1$t1$t1$S","$t2",'');
$choice=random(0,2,1);
$regex= "($t1$t1$t1)*$t2";
----------------------------------------------------
Problem text:

Given the following grammar:
<m eval="on">\[ G = (\{$S,$T\},\{$t1,$t2\},R , $S) \]</m>
with the set of rules <m eval="on">$ R $</m> containing the following rules:
<m eval="on">\[ $S \to $productions[0]\ |\ $productions[1]. \]</m>

<p />Form four terminal words for this grammar:<p />

----------------------------------------------------
// then: get students answer and save to answer[0]...[3]
---------------------------------------------------
//Answer algorithm again in Perl:

$credit = 0;
for ($i=0;$i<4;$i++){
   $k=0;
   while (($answer[$k] ne $answer[$i]) && ($k<$i)) { $k++; } 
   if (($answer[$i]=~/^$regex$/) && ($k == $i))
      {
        $credit = $credit+1;
      }
}
if ($credit > 3.5){
   return 'EXACT_ANS';
} else {
if ($credit < 0.5){
   return 'INCORRECT';
} else {
   return (ASSIGNED_SCORE, $credit/4.0);
}}</answer>
 
For more complicated problems (to check a regex given by a student, I use a LON-CAPA-Perl Library written by a collegue, I guess it constructs words from the teachers and the students regex and compares the outcome)

**Comment by nfa019** [comment] 2020-01-30 11:13
So I tried something in maxima (more ot less the problem above) using the commands seen here:
https://github.com/andrejv/maxima/blob/master/share/stringproc/sregex.lisp


load("sregex");
regex:regex_compile("(aaa)*b");
str:"aaaaaab";
regex_match(regex,str);
boolMatch:member(str,regex_match(regex,str));

This would deliver true, but in the list regex_match(regex,str) are [aaaaaab, aaa] and not [aaaaaab,aaab,b]. 

For me, the regex (aaa)*b stands for an arbitrary number of aaa (triple a) followed by a single b and I would expect this for (all) dialects of regexes, too (it is such a simple regex)
![maximascrot](https://user-images.githubusercontent.com/1466212/73444733-7c03de00-4359-11ea-99de-5290fabf008e.png)

**Comment by aharjula** [comment] 2020-01-30 14:29
Hmm... For me that `(aaa)*b` would also mean similar things, compiling the regex can probably be skipped if there is no repeated use of it but indeed the results seem to be like this and I feel like it tells pretty clearly if there was no match:
```
(%i8) regex_match("(aaa)*b","aaa");

(%o8) false
(%i9) regex_match("(aaa)*b","aaab");

(%o9) ["aaab","aaa"]
(%i10) regex_match("(aaa)*b","aaaab");

(%o10) ["aaab","aaa"]
(%i11) regex_match("(aaa)*b","aaaaab");

(%o11) ["aaab","aaa"]
(%i12) regex_match("(aaa)*b","aaaaaab");

(%o12) ["aaaaaab","aaa"]
(%i13) regex_match("^(aaa)*b$","aaaaaab");

(%o13) ["aaaaaab","aaa"]
(%i14) regex_match("^(aaa)*b$","aaaaab");

(%o14) false
```
It seems to return pretty logical things the matched part and collected groups and those parenthesis do declare a group. In any case I would rather write the `boolMatch` like this as to me that pattern does not have `^` or `$` to anchor it to the ends of the string and thus any match should be enough:
```
boolMatch : is(false # regex_match(regex,str));
```
If the anchors are implied then but not part of the pattern then you would need to compare the first item in the returned list to whatever went in to decide if it is the full string or not.

I don't quite understand this: 
", but in the list regex_match(regex,str) are [aaaaaab, aaa] and not [aaaaaab,aaab,b]."
Do you want or is there are reason why you would want that later, or was that just because you chose to use that `member()`-logic? And I know of no regexp (I am not a fan of them and thus do not know many) that would return that, to me it returns first the bit that matched the pattern and then apparently selected groups, and it considers `(aaa)` a group in a pretty normal regexp way.

**Comment by nfa019** [comment] 2020-01-30 15:25
well, the whole string itself should match the regex, not only a part of it, that's why I did the member check.

what disturbs me is that aaa is considered a match, but it doesn't contain a "b"

**Comment by aharjula** [comment] 2020-01-31 06:56
> well, the whole string itself should match the regex, not only a part of it, that's why I did the member check.
> 
> what disturbs me is that aaa is considered a match, but it doesn't contain a "b"

Ok in that case the pattern `(aaa)*b` is simply wrong and we have to consider the possibility that the environment that previously executed it wrapped it automatically into something. The safest bet would be wrapping in parenthesis and thus making the whole pattern a capture-group, like this:
```
(%i30) regex_match("((aaa)*b)","aaaab");
(%o30) ["aaab","aaab","aaa"]
```
The parenthesis around `aaa` led to it being captured into the result, so wrapping the whole thing captures the whole thing. Note that in a latter example below you will see what happens if the capture target does not exist. So `aaa` is just a match of that particular capture-group not the full match.

However, that still leaves it to you to check that the whole string is present in the set to decide if it is a full string match. The other an also likely option is that the system has added the anchors for string start and end around the pattern, like this:
```
(%i31) regex_match("^(aaa)*b$","aaaab");
(%o31) false
(%i32) regex_match("^(aaa)*b$","aaab");
(%o32) ["aaab","aaa"]
(%i33) regex_match("^(aaa)*b$","b");
(%o33) ["b",false]
(%i34) regex_match("^(aaa)*b$","aaa");
(%o34) false
```

If I had to guess I would go for the anchoring option from the point of view of the system, but it one goes for that one needs to consider the possibility of white-space around the string and if it should be trimmed before the pattern match or if the pattern itself should deal with it.

If you automatically convert patterns from existing systems you may wish to wrap them during the conversion. I am pretty sure that STACKs regexp will not do such wrapping as it lessens the control of the author.

**Comment by aharjula** [comment] 2020-01-31 07:01
And if that `b` is still something you miss you will need to consider some other sort of pattern as I know of no regexp-implementation (again I don't know many) that would return it at all for `(aaa)*b`, in any case other than full match to a string not having any triplets of `a` before `b`, as it is not inside any capture group, especially it itself is not inside any capture-group.

**Comment by nfa019** [comment] 2020-01-31 08:55
It would also find a single b
`(%i2) regex_match("(aaa)*b","b");
(%o2)                             [b, false]
`
I only did not expect, that it also delivers the capture group, for my purposes I think I can live with it.
The pregexp doc (http://ds26gte.github.io/pregexp/index.html) says

>  It provides regular expressions modeled on Perl’s

so "my" regexes should work. I know, that I have to use it in another way as in Perl itself (I think, this has to be done by hand, we only convert the structure of the problem, converting Perl code into Maxima is more or less not possible (or only in very very simple cases))

**Comment by nfa019** [comment] 2020-01-31 12:36
So, I wrote my first question with sregex loaded:

[quiz-Testkurs-Regex Test.xml.zip](https://github.com/maths/moodle-qtype_stack/files/4139274/quiz-Testkurs-Regex.Test.xml.zip)

I think, I can work with it.

**Comment by sangwinc** [comment] 2020-02-01 09:47
Thank you very much for doing the background work here.   I think we can certainly add in the load command.

Would you like an answer test, and if so how would you like it to work?   Tests only return true/false.  We can very easily create a supported answer test which establishes that the student's answer contains a pattern supplied by a teacher.  Is that something you would want?

**Comment by aharjula** [comment] 2020-02-01 10:17
Chris,
Well, I would want one, but we would need to come up with a new name. We cannot just use the old name as this would probably not use the same patterns and in any case, the patterns would need to go in as Maxima-strings with the escaping. Also, the new test should only allow real string values on the sans-side i.e. coming from string inputs (or in the future through the string-values map in the compiled PRTs).

**Comment by sangwinc** [comment] 2020-02-01 10:30
Indeed!

What about sregex?

Yes, the test will have to enforce sans as a string.  Teachers can do string(ans1) in the feedback variables if they want something else.

Chris

**Comment by aharjula** [comment] 2020-02-01 10:43
"sregex" would directly tell what happens so why not. Few points:
- No need to compile the pattern in the answer-test as it is used just once there.
- I would really like to enforce `sans` needing to be a string, but we do not have the means for doing that in the current model. So you will probably add a type check into the Maxima side logic to turn it into a string if it is not.
- The pattern should be given as a Maxima string as then it can be randomised e.g. in question-variables like some people randomise sig-fig requirements.

**Comment by aharjula** [comment] 2020-02-01 10:57
Also, does the pattern go to test-options or to `tans`? Which makes more sense? Did we have `simp:true` in options, if then that might be the safer place?

**Comment by sangwinc** [comment] 2020-02-01 14:29
What about this?

https://github.com/maths/moodle-qtype_stack/commit/5f979eefc11db82fceee1fc4f57a8b43d180eb89

Please can you add more tests?

**Comment by aharjula** [comment] 2020-02-01 15:02
Chris, I'll try to come up with some examples.
The next step would now be to rewire the String and StringSloppy tests to use this on the background. But they too have the problem of what exactly is in the `sans` and `tans` fields, previously they have somehow managed to deal with value without escaping and even raw input values, but in the long run having actual strings would be better for consistency.

**Comment by nfa019** [comment] 2020-02-03 09:45
> Thank you very much for doing the background work here. I think we can certainly add in the load command.

Thank you, This will help

> Would you like an answer test, and if so how would you like it to work? Tests only return true/false. We can very easily create a supported answer test which establishes that the student's answer contains a pattern supplied by a teacher. Is that something you would want?

If this was a question for me: mybe for some question, I didn't think of yet. For the questions, I have in mind at the moment, I just need, that the student string fits exactly the teachers pattern. But this can be solved like in the stack question I posted above. So I have my algorithm for that and only a handfull of questions where I need it. So I'm fine with sregex included in the load command.

**Comment by aharjula** [comment] 2020-02-03 10:06
I guess the question was for both of us. In any case we seem to have arrived to a result where:
 1. we add `load("sregex");` into the default logic, thus removing the need to modify anything by hand
 2. there is going to be a new answer-test for the PRTs that uses `sregex` to match patterns and people will be guided to use it if they needed the old regexp test.

As answer-tests in the PRT can only return a boolean result the test there will naturally not care about any capture-groups in the pattern so if one would need to extract something from the string it would always need to happen at the feedback-variables anyway. Based on your example I would indeed guess this is now done but I'll leave it to Chris to close this once the work gets merged.

**Comment by sangwinc** [comment] 2020-02-03 17:33
Yes, if you want capture groups you need to use the feedback variables as tests can only return true/false.  Please do add test cases!

**Closed** 2020-02-04 10:18 UTC
