### ISSUE TITLE
Question note character limit

### ISSUE THREAD

**Issue by lentzi90** [maths/moodle-qtype_stack#198] opened 2016-03-12 09:26 UTC
Is there a reason for having a 1024 character limit on the question note?
I ended up with about 1050 characters in a really big question with many different parts, and got an error message about this limit.

**Comment by aharjula** [comment] 2016-03-12 10:02
So you are running the abacus-branch... The master still has a 255 char limit. I will happily raise that to 2k or 4k if need be but after that we start to have issues about the sense of raising it further as the technical purpose of that field is to generate keys for identifying different variants of the question and at some point the key length starts to be an issue in that comparison. Especially, when we typically do not have millions of variants and 1k chars should be enough to describe millions of variants. The reason for there being a limit is just space and comparison time related, but as that is something that only affects the variant pre-selection process it is not that critical, but I can imagine various future needs that might benefit greatly from smaller keys, so I would prefer smaller keys even though I was the one who raised it from 255 to 1024 the first place.

Please do explain how you are using the field so that the other developers understand the need and start to understand why they should have this change in the system. Especially, so that they would make this change to the current master branch.

An about that question, when you say big how big? Number of random parameters, inputs, PRTs? Is it typical for you to have this big questions and can you see there being even bigger ones? I.e. if you were to imagine a distribution of your question sizes how large a portion of the questions would be smaller than this? Just interested as it has been me that typically wants to support bigger questions...

**Comment by lentzi90** [comment] 2016-03-12 11:24
Thanks for the fast reply!

Yes, I'm running the abacus-branch (working for @alcarola ).

I try to keep the notes short, but still meaningful on their own: a short version of the question text + answers. If necessary, I could write them even shorter by skipping the question text and just write one or two words to describe each answer + the data given. However, I like to be able to se what the question is about just by looking at the notes, but this is really just "nice to have", not "must have".

This big question is about hypothesis testing and linear regression. It has 12 inputs, 11 PRTs and 12 random parameters (data points). I think it is safe to assume that this is the biggest one I will ever handle. If the question got any bigger I would definitely want to split it up into smaller ones just to make it easier to edit and handle.

**Comment by aharjula** [comment] 2016-03-12 16:28
Thanks for the size description, that is indeed a very big question and the usage description matches pretty much the way I like the question note to be used. It is obvious that the 255 char limit would have been difficult for you and 1024 is a bit too close. I'll up the abacus side to 2048 when I push that STACK 3.5 + abacus merge next week and hopefully the master branch follows the lead at some point.

**Comment by lentzi90** [comment] 2016-03-12 17:32
Ok, thank you for the help! :)

**Comment by aharjula** [comment] 2016-03-14 07:33
Oops, can't actually give you 2048... The database abstraction layer used in Moodle says:

"Coding error detected, it must be fixed by a programmer: Invalid field definition in table {qtype_stack_options}: XMLDB_TYPE_CHAR field "questionnote" is too long. Limit is 1333 chars."

I'll up it to 1300 chars and leave the chosen number a mystery for others to solve.

**Comment by timhunt** [comment] 2016-03-14 15:15
The limit is acutally due to the limitation of Oracle storing UTF-8 strings, and Moodle needing to work cross-DB.

Note that the question note is just meant to be a breif summary of which variant of the question this is. It is not meant to duplicate the entire question.

**Comment by aharjula** [comment] 2016-03-15 11:01
Yes it indeed needs to be a brief summary that differs for each variant so that we can choose those distinct variants automatically in our simpler questions, but as we might actually want to apply some other filters than just distinctness to our variant selection for the more complex questions we may need to provide additional information in that note. And providing that information typically means that we need to tell more than just the raw parameters to the teachers so that the teacher does not need to find out the features he is seeking starting from those parameters. The problem is that the bigger the question becomes the more there typically are of those specific features and combinations of them which makes it very nice to have descriptions that tell the teacher directly which type of an variant this variant is.

Naturally, in the conditional-blocks branch (i.e. abacus) you can even add conditionally rendered flags to help you mark the variants with the features you want. And writing that kind of code into 255 char castext field just was not feasible so I upped the field size and would probably grow it even more if the field were not limited, but I understand the limit and can accept the current size limit of 1300 now that Lennart has given us an example of a truly large question and how much it would need, and that example tells us that the new limit is reasonable.

By features I mean typically the methods required for solving the question with the specific parameter combinations or possible short-cuts present with the combinations. The features may also be interpreted as difficulty. Naturally, the question variants may provide very different questions and therefore we want to see what we are selecting from that set and we want STACK to do the work and calculate for us the details so that we do not make mistakes when selecting. And no we do not believe that we should separate the different variants to different questions, it is much more convenient to invest time to make one question perfect than to provide multiple ones also we do not like to have the variant type selection hidden in the question code, the teacher might then make even more mistakes modifying it.

**Comment by aharjula** [comment] 2016-03-15 11:09
Now that I think of it... Tim, could the variant selection thing have a regexp filter or some such that would search for specific things ("I don't like variants with the number 7 in them...", "drop variants that say that they have double roots", "90 degree angles must not be present") in the question-note and allow dropping of variants based on that? Now the teacher just gets a random set and goes through of the by hand dropping those that do not fit his needs, if we had a filter that would do the first passes based on the details provided in the question-note things would be more efficient.

**Comment by aharjula** [comment] 2016-03-15 11:15
Ahh... never mind the question tests do that in some sense even though they are way more complex solution for this.

**Comment by sangwinc** [comment] 2016-08-19 13:03
Dear all,
Can we agree what we want to do and close this issue?
Chris

**Comment by aharjula** [comment] 2016-08-19 13:08
Abacus branch uses 1300 char question-notes and I see no reason why the master should not do the same. I believe the question note could be do lots more than just being an identifier for unique variants of the same question but that is another issue. What is certain is that 255 is way too small a field size for this.

**Comment by sangwinc** [comment] 2017-06-06 16:13
This has been changed in v3.5.7.

**Closed by sangwinc** 2017-06-06 16:13 UTC
