### ISSUE TITLE
Validation of matrix of variable size sometimes misses "-" sign

### ISSUE THREAD

**Issue by azeiser** [maths/moodle-qtype_stack#654] opened 2020-11-17 11:12 UTC
Sometimes minus signs are missing in the validation field of a matrix of variable size:
![screen05](https://user-images.githubusercontent.com/45635094/99382992-964d7f00-28cd-11eb-94ee-9c865a63052e.jpg)

If one makes the input field bigger, the signs appear again:
![screen04](https://user-images.githubusercontent.com/45635094/99382982-93528e80-28cd-11eb-91e4-d245a9422c0a.jpg)

This happens on Firefox 82.0.3 on Windows. I could not create a more easy question to reproduce the error.

**Comment by m-r-k** [comment] 2020-11-17 13:24
Actually, this is strange, because resizing the input should not trigger a new validation.
But I cannot reproduce the problem myself.

Could you perhaps attach the question as XML?

A debugging possibility would be to open the browser toolbox of Firefox and select the missing minus signs with the inspector tool.
Or maybe errors are already shown in the console?

**Comment by azeiser** [comment] 2020-11-17 14:09
It's a really strange thing: I tried to reproduce the error with the original question - it didn't work, meaning everything is fine. Hence I could not inspect it.  I attach it nevertheless. 
[quiz-M2 (PÜ)-163857-9-Export_matrix_bug-20201117-1505.zip](https://github.com/maths/moodle-qtype_stack/files/5553920/quiz-M2.PU.-163857-9-Export_matrix_bug-20201117-1505.zip)

**Comment by sangwinc** [comment] 2020-11-17 14:15
There are quite a few different minus signs in unicode and my guess this answer was copied and pasted into the input.  That might explain why the minus sign is "lost".  Is that possible?

**Comment by m-r-k** [comment] 2020-11-17 19:33
@azeiser I tried your question. No problems; seems okay to me.
Should we close this issue then?

**Comment by azeiser** [comment] 2020-11-18 09:16
@sangwinc It's possible that the answer has been copied and pasted by a student. I tried it myself but I couldn't reproduce the error.

@m-r-k Sure. Would you be interested in this issue if I could find an reproducible example later?

**Comment by m-r-k** [comment] 2020-11-18 09:36
Great. When we have a reproducible example, we simply reopen the issue.

**Closed by m-r-k** 2020-11-18 09:36 UTC
