### ISSUE TITLE
Broken communication between JSXgraph and STACK?

### ISSUE THREAD

**Issue by aacchhee** [maths/moodle-qtype_stack#1017] opened 2023-08-22 08:06 UTC
We have a couple of questions that should be answered by manipulating points on the JSXgraph diagram. They worked last year, but after upgrade to Moodle4 and stack 4.1.4+ we are getting an error when evaluating student's answer.

TypeError: null is not an object (evaluating 'doc.querySelector('input[id*="_ans1"]').value’)

A colleague of mine made a hack that dives deeper in JSON structures, so that questions work. But it seems wrong to re-implement what was working before.

I attach an old question that worked last year and a fixed question that works now.

[questions-imax1002-Grafisk-20230822-0953.zip](https://github.com/maths/moodle-qtype_stack/files/12406453/questions-imax1002-Grafisk-20230822-0953.zip)

**Comment by aharjula** [comment] 2023-08-22 09:01
In STACK 4.4.3, we switched executing JSXGraphs inside a sandbox so that no code inside the graph can affect the VLE side logic directly, either maliciously or by accident (accidentally breaking the Moodle JavaScript is common enough occurance). This is one of the steps to finally secure STACK materials so that no matter what material you get and no matter where you get it, you can use it without any fear of malicious content affecting things. Basically, [STACK-JS](https://docs.stack-assessment.org/en/Developer/STACK-JS/) is a way to limit the possibilities of the author to do things to the VLE to certain preapproved actions so that we can make sure that things are safe. Unfortunately, it also means that old custom bindings relying on JSXGraphs are probably going to suffer, but those can either be fixed by dispatching those change events, for requested inputs, as in your example or by moving to the new custom-binding logic.

In your failing example there are two different things that cannot work:
 1. Directly trying to query-select the ans1-input, won't work as no such input has been requested either by using STACK-JS logic or by declaring it as bound as an attribute to the `[[jsxgraph]]`-block. Basically, to fix that, use the provided means to access inputs. Had it been requested, then it would have been selectable, although not with that underscore in its name.
 2. Reading the `innerHTML` of an element outside the `[[jsxgraph]]`-block is something new, and if it is really what you really want to do, we could possibly add an API function for fetching such information. However, it would be asynchronous, which would make things somewhat more complicated for those that want to use it. We already have such a function for tooling the visibility of such VLE side elements and even one that allows one to [set the contents](https://github.com/maths/moodle-qtype_stack/blob/ec5cc8e6dffb2b915c2fa682870e2c1ef8af396a/corsscripts/stackjsiframe.js#L231-L238) of such elements (naturally one cannot inject scripts).

In the longer run, this is the route we will be taking, and we will push for security using sandboxes and controlled interfaces as it provides the added benefit of simplifying material sharing over VLE boundaries, as long as those VLEs implement those interfaces.

If you, for some reason, need to quickly revert things to work as they were before, you can simply copy the whole /amd/ directory and the /stack/cas/castext2/blocks/jsxgraph.block.php file from the 4.4.2 release. You will miss some of the newer stack_jxg features, but then you were probably not using them anyway.


As a warning for all scripting, the plan is that at some point in the future, all scripting in STACK-questions will be forbidden if it does not execute inside one of these managed sandbox iframes. So If you choose to migrate your logic outside of the `[[jsxgraph]]` and instead set up your own `<jsxgraph>` etc., which will happily run those scripts, you will eventually find yourself in the same trouble. That might be far in the future, but it is coming, the plan is to mature this STACK-JS interface for those preapproved actions that one can do, but there is always the possibility that we need to push forward faster should someone really create something malicious that needs to be stopped fast. Should one wish to start migrating any heavier scripts that they may have and which execute outside of `[[jsxgraph]]`-blocks, we do now also have a `[[javascript]]`-block, which allows one to bind to inputs without the need to drag JSXGraph into the picture. There is also the `[[iframe]]`-block that allows one to inject anything inside the question, e.g. some other plotting library and connect it to inputs through scripting.

**Comment by aharjula** [comment] 2023-08-23 06:30
The `stack_jxg.custom_bind` function mentioned in #776 finally got out in the 4.4.3 release, and it is the path I recommend and intend to support for a long time.

You can still act (see its value, set its value and receive change events, but nothing else) on an input element as well if you really need to, but then you will need to request access to it, and the simplest way is through those `input-ref-` attributes of the `[[jsxgraph]]` block. However, setting the value of an input through such a route requires one additional step to function. You now need to notify STACK-JS about that change, and that happens by dispatching a change event for that input.

In the longer run, as long as what you do is being done with inputs received through the `input-ref-` attributes or the new asynchronous [`stack_js.request_access_to_input`](https://github.com/maths/moodle-qtype_stack/blob/ec5cc8e6dffb2b915c2fa682870e2c1ef8af396a/corsscripts/stackjsiframe.js#L164) and are limited to reading and writing its value or listening to changes of that value then you can be pretty sure that still will be a stable and future proof way. And if you do whatever you do through `stack_jxg` or `stack_js` functions, we will work hard to make it so that if something changes, those will keep on working.

**Comment by aacchhee** [comment] 2023-08-31 16:05
It seems that none of our legacy questions of the kind where input is coming from jsxgraph work after these changes.

This applies also to @georgekinnear 's example questions here: https://stack-demo.maths.ed.ac.uk/demo/course/view.php?id=18

**Comment by sangwinc** [comment] 2024-03-26 15:01
@georgekinnear, please would you double check the questions mentioned here and let me know if this is an authoring issue or a plugin bug which needs to be addressed for the next release.

**Comment by georgekinnear** [comment] 2024-03-26 17:24
The link is broken now since stack-demo was updated, but I think this was referring to the JSXGraph demo that is now here: https://stack-demo.maths.ed.ac.uk/demo/course/view.php?id=4

Indeed many of the questions there are now broken because they use old javascript code that is no longer supported.

**Comment by sangwinc** [comment] 2024-03-26 17:28
Ok, just to confirm.  This is a "question authoring" issue that can be fixed by authoring the question to the current STACK-JS guidelines?  It's not a bug in the STACK plugin?  If so, I'm really sorry we broke all your questions @georgekinnear.  If there is a bug with the STACK plugin, please raise a new issue.

**Closed by sangwinc** 2024-03-26 17:28 UTC

**Comment by georgekinnear** [comment] 2024-03-26 17:57
Yes, it's definitely fixable - and in fact now much easier to create questions of that type, with supported JS code built in to the system!

**Comment by georgekinnear** [comment] 2024-03-29 09:14
@aacchhee - just to note, I have now fixed my broken questions! The questions under "TALMO 2023" in this course should all now be working: https://stack-demo.maths.ed.ac.uk/demo/course/view.php?id=4

The fix was actually quite minor - I just needed to add `stateInput.dispatchEvent(new Event('change'));` in the right place, to make sure that any changes in the JSXGraph values were passed back to the hidden input field in the STACK question.
