### ISSUE TITLE
Questions not working with latest STACK

### ISSUE THREAD

**Issue by timhunt** [maths/moodle-qtype_stack#844] opened 2022-08-22 15:45 UTC
The attached question worked find (all questoin tests passed) in STACK 4.3.11. It is faiing with the latest dev branch (~4.4.0).

I don't get a validation error when editing the question, but on the question test page we get 

> 0 passes and 1 failures.
> This question generated the following errors at runtime.makelist: the fourth argument minus the third one must evaluate to a number; found: (16.0-1.0)+0.0*(-1.0) The field ""Question text"" generated the following error: makelist: the fourth argument minus the third one must evaluate to a number; found: (16.0-1.0)+0.0*(-1.0) The field ""Question variables"" generated the following error: makelist: the fourth argument minus the third one must evaluate to a number; found: (16.0-1.0)+0.0*(-1.0) 

I don't understand this, so I am hoping you can see what is going on. Thanks.

[makelist-problem-question.xml.txt](https://github.com/maths/moodle-qtype_stack/files/9395734/makelist-problem-question.xml.txt)
1

**Comment by timhunt** [comment] 2022-08-22 15:51
Here is another.

This one leads to the particularly Zen error message

> 2 passes and 0 failures.
> This question generated the following errors at runtime. General feedback: No error.
> 
> This question generated the following errors at runtime.No error. 

[no-error-question.xml.txt](https://github.com/maths/moodle-qtype_stack/files/9395788/no-error-question.xml.txt)

**Comment by timhunt** [comment] 2022-08-22 15:56
This one gives

> 3 passes and 0 failures.
> This question generated the following errors at runtime. General feedback: apply: subscript must be an integer; found: 1+1
> 
> This question generated the following errors at runtime.apply: subscript must be an integer; found: 1+1

[subscript-must-be-int-questions.xml.txt](https://github.com/maths/moodle-qtype_stack/files/9395831/subscript-must-be-int-questions.xml.txt)

**Comment by aharjula** [comment] 2022-08-22 15:58
Almost certain this is #824, the second one is probably also that but the error message is broken. There is a branch with a fix that will fix most things but not all things are fixable due to the magical way `ev()` affects evaluation order and how that does not quite work with the new security system, that does checks during runtime, which also affects evaluation.

Some materials may need to have some manual interventions to rewrite complex `ev()`-calls that do too many things, either by splitting them into parts or using other functions that have simpler evaluation order.

All those, "must be integer" ones are basically due to the evaluation order and its affects on simplification, those should be fixed in the issue branch.

**Comment by timhunt** [comment] 2022-08-22 15:59
I think this is the last one (for now)

> caslines_to_answer could not create the answer.
> 
> [More information about this error](https://learn1acct.open.ac.uk/admin/tool/redirector/redirect.php/400/en/error/qtype_stack/exceptionmessage)
> Debug info:
> Error code: exceptionmessage
> Stack trace:
> 
>     line 1302 of /question/type/stack/stack/input/inputbase.class.php: stack_exception thrown
>     line 967 of /question/type/stack/stack/input/inputbase.class.php: call to stack_input->caslines_to_answer()
>     line 673 of /question/type/stack/stack/input/inputbase.class.php: call to stack_input->validate_contents()
>     line 731 of /question/type/stack/question.php: call to stack_input->validate_student_response()
>     line 976 of /question/type/stack/question.php: call to qtype_stack_question->get_input_state()
>     line 1056 of /question/type/stack/question.php: call to qtype_stack_question->has_necessary_prt_inputs()
>     line 998 of /question/type/stack/question.php: call to qtype_stack_question->get_prt_result()
>     line 774 of /question/type/stack/question.php: call to qtype_stack_question->can_execute_prt()
>     line 639 of /question/behaviour/behaviourbase.php: call to qtype_stack_question->is_complete_response()
>     line 683 of /question/behaviour/behaviourbase.php: call to question_behaviour_with_save->is_complete_response()
>     line 114 of /question/behaviour/adaptive/behaviour.php: call to question_behaviour_with_save->process_save()
>     line 207 of /question/behaviour/adaptivemultipart/behaviour.php: call to qbehaviour_adaptive->process_save()
>     line 1356 of /question/engine/questionattempt.php: call to qbehaviour_adaptivemultipart->process_action()
>     line 741 of /question/engine/questionusage.php: call to question_attempt->process_action()
>     line 87 of /question/type/stack/stack/questiontest.php: call to question_usage_by_activity->process_action()
>     line 391 of /question/type/stack/questiontestrun.php: call to stack_question_test->test_question()

[caslines_to_answer-could-not-create-the-answer-question.xml.txt](https://github.com/maths/moodle-qtype_stack/files/9395842/caslines_to_answer-could-not-create-the-answer-question.xml.txt)

**Comment by timhunt** [comment] 2022-08-22 16:09
Ah! one more. This one, you cannot interract with at all, becuase it takes so long to process. I strugged to get the error message, but I think it is like

> Fatal error: Maximum execution time of 60 seconds exceeded in /var/www/html/moodle/question/type/stack/stack/maximaparser/MP_classes.php on line 83  

[times-out-question.xml.txt](https://github.com/maths/moodle-qtype_stack/files/9395913/times-out-question.xml.txt)

**Comment by timhunt** [comment] 2022-08-22 16:35
> Almost certain this is #824, ...

Thanks Matti, that is useful information. Hopefully it will be possible to make some progress there, becuase otherwise it looks like we might have quite a lot of questions that need to be fixed.

(After as STACK upgrade, there are sometimes a small number of questions that need to be fixed, but hopefully not too many!)

**Comment by sangwinc** [comment] 2022-08-22 17:11
Matti, can we merge the current #824 code into dev? I'm planning to release a new version early next week so we can get these fixes onto our live server.  We've been testing the new code, and it all looks very positive.  Thanks for all your work here.

**Comment by aharjula** [comment] 2022-08-22 17:17
Chris, PR https://github.com/maths/moodle-qtype_stack/pull/838 exists for you to decide if you want to do that. To me, it seems like the best solution I can come up with, it is not perfect as we cannot replicate Maxima `ev()` exactly and at the same time maintain that security system.

**Comment by aharjula** [comment] 2022-08-23 11:05
Slowly, going through these, probably none are actually #824 more about serialisation no longer happening, so things that are unevaluated stay so as they do not travel to PHP and get injected back to CAS for the text rendering, instead they get used immediately in the CAS as the text rendering happens during the same session. As we do that, the rules for simplification tend to be tuned quite often.

The first example is a case where those rules have actually changed and do have an effect. While the new CASText2 logic does simplify things, if simplification is on (or gets adjusted during the injection), it does the final render to LaTeX portion in `simp:false`. The problem is that that `texput`-rule in use within the first question contains a `makelist`-call, `makelist` being a function that cannot work when `simp=false` and that `texput` rule gets activated during `simp:false`.

One could try removing the offending `simp:false,` from the start of this line, and if it still goes through the tests for CASText2 then it would be an extraneous bit of code, but I feel like it is there for a reason:
https://github.com/maths/moodle-qtype_stack/blob/84cdef23d3eecbb3576c3302038a9e4becbf9829/stack/cas/castext2/blocks/latex.block.php#L64

Generally, I think that having a `texput` rule that does not work when `simp=false` might also be something that should not be supported, as one could be expected to use those in both contexts even without STACK being in the picture. In that particular case turning simplification on within the `texput`-rule could be the quick fix:

```
/* From this: */
texmtab(e):=block([T,r,str],[T,r]:...
/* to this: */
texmtab(e):=block([T,r,str,simp],simp:true,[T,r]:...
```

**Comment by timhunt** [comment] 2022-08-23 11:18
Confirmed, I pused the latest version of STACK dev branch to our test server this morning, and these qusetions are all still failing in the same way.

If these questions no longer work, this is quite a serious backwards-compatibility break.

**Comment by aharjula** [comment] 2022-08-23 11:26
The second one goes to Chris. I guess it is related to unpacking the security feature within an answer test.

Tim. Did that push include a version number change? Did you clear all the caches before you did the run if there was no version number changes that would have triggered a full cache purge?

Those doing random things at the source code level need to be aware that if they do not update versions when they touch anything that modifies the question compilation logic they need to clear the compilation cache. The simplest way to do that is with this command. Of course if none of the questions were related to #824, clearing the cache was unlikely to do anything.
```
> php question/type/stack/cli/clearcascache.php --ccc
```
In normal operation you do not need to clear that cache at any point and doing so would mean significant performance penalties especially if done during production time.

**Comment by aharjula** [comment] 2022-08-23 12:07
Third one is more of the first one. I.e. a `texput` construct that is unable to work within `simp:false`, here a for loop generating indices for a subscript. Quick testing says that it is possible to remove that `simp:false,` bit from the code but it won't fix this as `simp:false` may be active elsewhere and will leak all the way down to that level.

Now if only those error messages were to display the path to the original source of the issue, it it present in the error objects and would simplify spotting the source, especially with these `texput`-mods... Would help quite a lot with some of these samples...

**Comment by aharjula** [comment] 2022-08-23 12:25
Fourth seems to have plenty of things that cannot be called with `simp:false` but are for whatever reason being called in such a context even when no context switches are apparent. Somewhere there is a larger bug that switches the default simplification, and that probably is the reason why removing that `simp:false,` does not work.

**Comment by aharjula** [comment] 2022-08-23 13:00
The fifth one, the one timing out seems to explode in filter 996 (the new security system) and that is obviously a bug. It keeps rewriting code and never ends but why is still not clear. Probably the way a random thing gets `applied`, rewriting that as something that can be checked will be interesting for the filter to do.

**Comment by aharjula** [comment] 2022-08-24 07:55
That infinite runtime case should now be fixed. As to the others, I think they just cannot be supported in that form anymore and that the newer behaviour is more consistent. My reasoning is as follows:
 1. Any `texput` logic that affects validation messages simply must be able to be executed with `simp:false`. There are absolutely no way around that.
 2. `simp:false` is required for many very old test cases to work, i.e., that `{@1/0@}`.
 3. Given 1. it would be simpler to instruct people to write their `texput` logic to always work under `simp:false` than to note that other contexts could be constructed. Even when that particular rule is only used outside the validation message context.
 4. It would be possible to conditionally use a different start for that [line 64](https://github.com/maths/moodle-qtype_stack/blob/84cdef23d3eecbb3576c3302038a9e4becbf9829/stack/cas/castext2/blocks/latex.block.php#L64) in different parts of the question to enable different behaviour. But then those parts would not support 2.
 5. This is one of those highly advanced things that people do at the edges and which may break when the edges get more defined. In this case, the edges are advancing and, in particular, in the direction of validation messages, and that advance might bring new requirements to other parts of the question.

To me, the possibilities of validation message tuning far outweigh the requirement of all `texput` rules needing to be able to work with `simp:false`. So I would rather leave it like this and simply ask those that do these advanced things to control simplification inside their logic if they do things that require simplification, i.e., indexing things with values constructed by loops or other such things.

As to what broke, it is deep in the logic of CASText2 implementation of `{@...@}` and I see no fix that could cover all the requirements present in the CASText test cases and still manage to replicate the interesting simplification settings of the old multi-pass CASText system related to complex `texput` rules. If someone wants they may try replacing the logic in `latex.block.php` or possibly in the `ct2_latex` CAS side function (which is the place where one should do things if one does things), but I doubt a solution that would not consist of fall-back error handling that toggles `simp:true` exists and I really would not want to add any more error catching to that bit of generated code.

**Comment by timhunt** [comment] 2022-08-24 08:05
We have 6646 essentially different STACK questions (measured using `SELECT COUNT(DISTINCT questionvariables) FROM mdl_qtype_stack_options`).

Just telling people "we had to break backwards-compatibility, you have to fix it at your end", is nor very helpful.

Strict validation for newly authored quetions is good. Breaking backwards compatibility is not.

(But, I don't have time to dig into how many of our questions are acutally broken, and whether most of them are fixable with a bulk search-replace. I will get back to this in a few weeks when I have time to think. In the mean time, anything that can be done to reduce the breakage at the STACK end would be appreciated.)

**Closed** 2024-11-08 11:16 UTC
