### ISSUE TITLE
Equivalence reasoning and rational expressions with inequality

### ISSUE THREAD

**Issue by shinuito** [maths/moodle-qtype_stack#657] opened 2020-11-19 19:00 UTC
I was curious whether the current state of the Equivalence reasoning Input type could handle inequalities and in particular simple enough rational expressions.

I was thinking of the following type of question where you prove that a sequence was increasing.

<img src="https://user-images.githubusercontent.com/26803867/99708273-8aacb480-2a95-11eb-991c-80464015e8f9.png" width="500" height="300"/>

I understand Equivalence reasoning is still being developed so just wanted to test it out. It seems ok with the inequality which is cool. I presumed the reason it didn't like the cross multiplication step is because without further information it's not clear whether any of `n`, `n+1` or `n+2` were negative so it can't test the equivalence. (Or maybe it's something to do with the domains?)

I did try using different combinations of the `assume_pos`, `assume_real` input options as well as the question level options Assume Positive and Assume Real but that didn't seem to help the validation. (I did also separately try `assume(n>=1);` or `assume(n>0);` in the question variables but I'm not really sure if that was supposed to work anyway).

<img src="https://user-images.githubusercontent.com/26803867/99709704-81244c00-2a97-11eb-911b-4bc55dafc277.png" width="500" height="300"/>
It does seem like a really interesting question type, and if I'm not already doing something wrong maybe it wouldn't be far away from this type of question working :)

[SideNote: As is, I didn't include all the steps in the teachers answer as I just wanted a functioning question and to test whether this was possible yet . Similarly I'm only comparing the last lines, just again to get the question working to test - Still using STACK version: 2020070100 Maxima version: [5,41,0] and testing STACK version: 2020081700 Maxima version: [5,42,2]]

**Comment by sangwinc** [comment] 2020-11-20 16:10
Inequalities is an area where Maxima (and hence STACK) would really benefit from some stronger functions.  We made a start on this here: https://github.com/maths/moodle-qtype_stack/tree/inequalities

A colleague sent me a lot of very useful code, but then hasn't had time to help incorporate it into the existing STACK code.  So, this all stalled a little.  I would appreciate help in getting the solving inequalities part of the code working better.

**Comment by sangwinc** [comment] 2024-04-08 16:06
This is now a duplicate of issue #1018.

**Closed by sangwinc** 2024-04-08 16:06 UTC
