### ISSUE TITLE
Very minor: LaTeX/castext not rendered on question test page

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#169] opened 2016-01-04 09:31 UTC
I use the built-in mathjax filter in Moodle 3.0 and with my setup the question test page does not show rendered latex or castext.

**Comment by sangwinc** [comment] 2016-01-06 19:07
Ok, odd.  I've just installed a fresh Moodle 3.0 with the default settings, including the MathJax filter.

There is a problem if your question has no LaTeX in it.  Then the AJAX validation does not kick in. I know about this.   Other than this known issue, I can't reproduce the problem. Please can you be more specific?

Thanks for reporting this.

**Comment by alcarola** [comment] 2016-01-10 09:25
The following screenshot shows the problem:
![screenshot from 2016-01-10 11 18 51](https://cloud.githubusercontent.com/assets/1645276/12220867/79890086-b78c-11e5-9e2a-888509b89dcd.png)

I have the following filters enabled (in this order): MathJax, GEOGraph, JSXGraph

I believe the MathJax settings are at their defaults, but I am not completely sure:
![screenshot from 2016-01-10 11 24 17](https://cloud.githubusercontent.com/assets/1645276/12220876/cf58507a-b78c-11e5-8895-d7ec46093159.png)

**Comment by sangwinc** [comment] 2016-01-10 19:25
Thank you for reporting this bug.  I've committed a fix, but I'm sure Tim will correct me if this isn't exactly the right "Moodle thing".

**Closed by sangwinc** 2016-01-10 19:25 UTC
