### ISSUE TITLE
Answer tests harsher since Moodle upgrade

### ISSUE THREAD

**Issue by ianjones** [maths/moodle-qtype_stack#418] opened 2018-11-15 14:05 UTC
Hello.

Lecturers are emailing me that questions are getting marked wrong that last year were marked correct with the same input. Investigation as led me to believe that some answer tests are now harsher. The below question uses EqualComAssess. Now it marks "85" as correct and "85+0*I" as incorrect, whereas last year the latter would be marked correct. 

Has anyone else discovered something similar?

**Comment by timhunt** [comment] 2018-11-15 15:34
Well, we occasionally discover things like this, although I don't think I have seen exactly that.

The reason we find things like this is that our question authors are good, and write question tests. And, every time we upgrade STACK, we used the bulktest scripts to verify all our questions. That way we tend to find these problems before they hit students. It is really worth getting the "Write question tests" message out there.

**Comment by ianjones** [comment] 2018-11-16 09:31
Thanks Tim. As it happens this question does have question tests. That said I am not involved in Moodle upgrades and so I'm afraid don't know about bulktest scripts.

**Comment by sangwinc** [comment] 2018-11-16 10:06
Ian,
If you send me specific examples, I'll look into it.  At the very least we can add the examples you are relying on to our test cases to alert us if we change something you need.
Chris

**Comment by aharjula** [comment] 2018-11-16 10:15
Somewhat related wishes for a not unrelated scenario. But nothing to do with harshness...

Imagine that you are a teacher transferring questions (lets say about 100 questions for scale) from one Moodle to another. You are not the site-admin of neither Moodle nor do you have special permissions to access the STACK settings page or those scripts and you don't even know which versions of STACK are installed on those Moodles.

In that scenario do you have any means of running bulk tests? Or are you doomed to going through each question individually? I think I have talked about this at some point earlier but can't remember if there is a way.

In any case what I would hope for would be some sort of an way of invoking the bulk tester for a single question bank (branch/category whatever) or course. Could we have such a thing accessible to those users that have access to the relevant question bank? Could we dynamically add an item under "Course administration" section if the given course has any STACK questions or would we need to build a block to provide such a tool a link in the user interface? Naturally, such an block is an ugly solution as it requires the course admin to add that block, but we had pretty much such a block back in the STACK 2 days.

While Tim is in a situation where he has quite a good access to Moodle administration side most people do not have that kind of an situation and could find it difficult to pick up a phone and call a suitable permissions having person to run the bulk tester for a given category. In the worst cases that call might have a significant cost associated to it and given how long the bulk tester might take to run that cost might be quite large.


As to the original issue, did your update also update Maxima? Changes to Maxima could explain a lot, but Chris knows better...

**Comment by timhunt** [comment] 2018-11-16 10:21
Matti, good point: We did add a capability 'Access STACK author tools' or something like that, to allow non admins to use things like the bulk tester, but as you say, I don't need to rely on in, so it probably does not work well in practice. Making this sort of thing practical for individual teachers to use would be worthwhile when someone has time, but that is a separate issue.

Ian, if you want to give your server admin people my email address, I would be happy to talk to them about good practice around upgrading STACK, if that would help. (Or, I suppose I could write it up on my blog, or put it in the STACK docs, so it ends up in the public domain.)

**Comment by aharjula** [comment] 2018-11-16 10:46
Tim, ahh yes there was a capability will need to ask the people defining our Moodles roles to add that to some of them. Nevertheless, in a ideal situation we would not need to have a capability and the tools would just be there if you might need them. Such an ideal situation could help some people that have to deal with Moodle as a service style situations where they have no access to tuning permissions/capabilities and just having STACK is a lot.

Lets hope that we get some time from somewhere to do this at some point.

**Comment by sangwinc** [comment] 2018-11-16 12:32
I think if we can expose the bulk test to teachers without too much trouble, and by default, it would really encourage them to write question tests in the first place!

**Comment by sangwinc** [comment] 2018-11-18 12:01
Ian,
I'm sorry if any changes have caused you any problems here.  However, I don't think the behaviour of this test has changed for 3 years!  E.g. here, https://github.com/maths/moodle-qtype_stack/commit/a3ae9bd12fb4b4cf2c59537f593bc05a6b23d343 I added in further test cases (relevant to this issue) to show that "simplifications"  1/3*i -> i/3 (1*i=i) and the related 23+0*i->23 have not been done by this test for a very long time.

I strongly recommend you run the "bulk test script" to identify anything which has changed.

George asked for better functions for dealing with complex numbers and I added these recently (https://github.com/maths/moodle-qtype_stack/commit/f504101628eab8ccdd8818d5e521032543aa740c)  I'm always open to suggestions about more answer tests.  I can see a need for a test "Equality up to commutativity, and associativity, and using "identity operations" tidy up an expression".  That is another story.

If the questions you have were relying on the old behaviour then I think you were relying on an unintended behaviour, sorry!  So, I'm going to close this issue.

**Comment by ianjones** [comment] 2018-11-18 14:08
Thanks Chris. Maybe we can have a chat this week about how I run bulk test scripts.

I'm left scratching my head as to why these questions have changed how they behave since last year. One thing occurs to me: can a Moodle upgrade result in deployed versions of questions being deleted?

**Closed** 2019-03-14 07:02 UTC
