### ISSUE TITLE
 significantfigures does not work with very large or small numers

### ISSUE THREAD

**Issue by 45789595** [maths/moodle-qtype_stack#680] opened 2021-02-01 10:32 UTC
significantfigures funktion seems to fail if I try to use it with very high numers like 10^23 or very small like 10^-12. I believe that there was no such a problem about 3 years ago.

Moodle version: 3.8.7
Stack version: 2020101501
Maxima version: 5.38.1

**Comment by sangwinc** [comment] 2021-02-03 10:39
STACK depends on Maxima, and maxima is written in LISP.  We rely on the version of LISP you have for floating point support and there are lots of choices here.  This will be responsible for the problem.  If you can track down which lisp I'll document this better.

**Comment by 45789595** [comment] 2021-02-03 13:46
On new server we have (CentOS) Maxima with SBCL Lisp. The former was Ubuntu and Clisp. This former version did not have this problem, as fas as I remember.

**Comment by sangwinc** [comment] 2021-02-13 12:31
Well, each version of LISP is different.  Please could you send me some very specific test cases and I'll look at the various versions of Maxima I have available?  I'll at least document this issue so everyone is clear about the limits of what we can manage to deal with.  Pure mathematicians basically only need 0, 1, pi, e and i.  I know physics has more extreme tastes and I will do my best to support this as well!

**Comment by aharjula** [comment] 2021-02-13 12:52
Chris, I believe this yet more of #406 and the way we should explore would be to turn the values to bfloats before any operations. It seems like the bfloat-library is independent from the LISP interpreters so it would give the same results on more platforms. Bfloats are probably not as fast as native floats but they should help when dealing with comparisons between wildly different scale numbers which is what can happen when doing the sgi-figs tests where we transfer the decimal places before truncation. Sam problem is present in units conversions where multiplications between giga and nano prefixes combined to some small numbers have the same problems with floating-point accuracy.

#406 is more about the overflow of the range of floats but if we were to turn to bfloats then that overflow would be less of an issue.

**Comment by sangwinc** [comment] 2024-05-08 15:03
Yes, this is a duplicate of issue #406.  I'll close this and move the discussion there.

**Closed by sangwinc** 2024-05-08 15:03 UTC
