### ISSUE TITLE
Problem with AlgEquiv?

### ISSUE THREAD

**Issue by ItSSt-here** [maths/moodle-qtype_stack#614] opened 2020-08-12 18:34 UTC
A question asks the students to calculate the derivative of f where

`f:(atan(x))/((-2*x+1)^(1/6))`

(that's the "minimal" case I have found that produces this problem)

For SAns I enter g where:

`g: ((((1)/(1+x^(2)))*(-2*x+1)^(((1)/(6)))-((1)/(6))*(-2*x+1)^(-((5)/(6)))*(-2)*atan(x))/((-2*x+1)^(((1)/(3)))))`

(Messy, but correct)

For TAns I enter h where:

`h: diff(f,x)`

(This is: `atan(x)/(3*(1-2*x)^(7/6))+1/((1-2*x)^(1/6)*(x^2+1))`)

The system says that the answer is incorrect. (Not CAS timeout or something like that, really inequivalent)

I have a workaround that works: If I enter as SAns `simplify(g)` then it recognizes them as equivalent.
Actually, `simplify(g-h)` returns 0 as expected (I thought that this is precisely what AlgEquiv check).

So I have a workaround. But I have a feeling that I'm doing something wrong. Or is it a problem with AlgEquiv?

Thanks in advance.

**Comment by sangwinc** [comment] 2020-08-13 15:59
Thanks for this, it is a nice example.  Yes, the AlgEquiv basically does something like simplify(g-h) but in practice it can't really do this.  If you have (x-a)^6000 and I have (a-x)^5999 then when you simplify the difference you get a timeout.  So we actually have to avoid both expanding out and avoid factoring.  If, as you do, you know a lot about your expression then by all means  simplify(g-h).  You have both atan and fractional powers which are both problematic for different reasons.  I'm sorry AlgEquiv can't be perfect, (the problem is actually undecidable, so I could use that defence if I was feeling peevish!) but I've done my best.  So, I am going to close this issue but I very much appreciate your example.  

Ask your students compare the derivatives of
p1:atan((x-2)/(x-1));
p2:atan(2*x-3);

Also try this
p1:2/3*sqrt(3)*(atan(sin(x)/(sqrt(3)*(cos(x)+1)))-(atan(sin(x)/(cos(x)+1))))+x/sqrt(3);
trigrat(diff(p1,x));

p2:2*atan(sin(x)/(sqrt(3)*(cos(x)+1)))/sqrt(3);
trigrat(diff(p2,x));

There are some serious difficulties with atan!

Chris

**Closed by sangwinc** 2020-08-13 15:59 UTC
