### ISSUE TITLE
Segmentation fault using Maxima 5.43.2 and php ver 7.4.3

### ISSUE THREAD

**Issue by spinozarabel** [maths/moodle-qtype_stack#731] opened 2021-08-22 11:54 UTC
On a new install of Ubuntu 20.04 (on WSL2 in a Windows 10 machine), when I installed STACK and tried to run a health check script I got a CAS timeout with error of segmentation fault.
I tried running Maxima from the command line as myself (non root, non Apache2) and was able to.
When I tried running Maxima from command line as Apache2 user (www-data) it again gave a segmentation fault. So clearly www-data was having an issue launching Maxima.
I had to change the ownership of /var/www directory to www-data before I could successfully run the health check script. Before that I also  did: sudo su -l www-data -s /bin/bash to ensure that www-data has access to that and then I exited back to my own user.
After creating an optimized Maxima image and caching it, I changed the /var/www ownership back to root and this time I could run all of the STACK functionality.

This behavior is different from that in Ubuntu 18.04 and prior. Clearly, many users will not have access to their Apache2 document root and to make temporary ownership changes. Can this issue be fixed? Thanks

**Comment by aharjula** [comment] 2021-08-22 13:16
Basically, since Maxima started to build a cache of its own into the home directory of the executing user, people on Debian (not the only distro with this sensible behaviour) variants that tend to have the www-data users home directory as a read-only or not owned by the user have had a problem. There are sensible reasons for the default config for the apache users home directory so this is a conflict between Maxima and that way of setting up the directories (also note the differences in the environment).

Whether the segfault is tied to this is pretty much a moot point as you are meeting the problem related to the Maxima process not being able to create its cache (where it compiles versions of its scripts). Possibly on your 18.04 installation you used an older Maxima or otherwise avoided this issue. In general, we have three major routes forward, none of them is under our control:
 1. Seek changes in the packaging of Apache, this is not going to happen as the packaging is sensible for the majority of Apache users.
 2. Ask Maxima developers to provide/ensure a fall-back operation mode for cases where one cannot write that cache, this might happen but I think it would lead to bad performance. I doubt it makes sense to explore this.
 3. If one does not have access to the document root one is unlikely to be able to install Maxima so it seems like the easier route is to use an external Maxima-server e.g. GoMaxima or MaximaPool. Of course in that case things become even more complex as one needs to acquire that...

@sangwinc As the issue is related to the www-users home directory not being writable one has to wonder whether we could simply set the environment (point `HOME` to some writable temp when generating the image...) so that the home directory would be somewhere else. This might be a general solution, however, I fear that this would not necessarily be without adverse effects. I cannot currently say what those adverse effects would be but I am certain that where ever that directory would be it should not exist in Moodle data.

**Comment by sangwinc** [comment] 2024-05-08 14:51
This is a specific install issue, is old, and hasn't been replicated by many users I'm closing this issue to tidy up outstanding issues.

**Closed by sangwinc** 2024-05-08 14:51 UTC
