### ISSUE TITLE
Insert stars fails with specific letter pairs

### ISSUE THREAD

**Issue by dibevan** [maths/moodle-qtype_stack#635] opened 2020-09-25 07:25 UTC
Insert stars fails with the following letter pairs that correspond to Maxima functions: **fb kt lg nm np tr ug**. Other two-letter Maxima function names don't have the same effect (e.g. af, at, av, cf, cv, fv, gd, km, pv, rk, sf). I haven't checked for examples with 3 or more letters.

![nm-Bad](https://user-images.githubusercontent.com/71870465/94238133-ca2ca980-ff07-11ea-8679-d8b25a9847cb.png)

**Comment by sangwinc** [comment] 2020-09-25 14:41
David,
STACK "knows" that "fb" is a variable used internally.  This is defined here.
https://github.com/maths/moodle-qtype_stack/blob/master/stack/cas/security-map.json#L2444
On the other hand "af" is known to be a function.
https://github.com/maths/moodle-qtype_stack/blob/master/stack/cas/security-map.json#L476

Are you using the "single letter variable names" input option here?  We don't insert *s absolutely everywhere or otherwise "pi" would become "p*i" which would cause all sorts of other problems.

**Comment by dibevan** [comment] 2020-09-25 15:06
Chris,

Thanks for your reply. Yes, I'm using "insert stars for single letter variable names"; imho, much more pleasant for students.

I hadn't realised that fb, etc. were Maxima _variables_, like pi, not functions. So this makes sense and isn't any sort of bug. Btw, what do "f", "s" and "?" mean in the code? (It's sad that JSON doesn't permit comments.)

However, from a STACK perspective, are these seven Maxima variables of any real use? Would it not make more sense to "hide" them from STACK. 

For now, I'll try to avoid pairing n with m or p, or t with k or r, when the students might be expected to create products.

Best wishes,

David

**Comment by sangwinc** [comment] 2020-11-21 19:36
David, we are planning a wider revamp of how options for input validation is dealt with, so I'm going to close this specific request as the issue is now embedded in the future design list.

**Closed by sangwinc** 2020-11-21 19:36 UTC
