### ISSUE TITLE
Instant feedback doesn't follow forced language

### ISSUE THREAD

**Issue by lassikor** [maths/moodle-qtype_stack#879] opened 2022-11-15 09:23 UTC
Hi,
we have noticed that the instant feedback that STACK provides when typing the answer does not follow the language forced on the  course, if a user has chosen a different language in Moodle. Simple test case (tested in Abacus Moodle):

- Force the course language to be different than yours in Moodle
- Open a STACK question on that course and type something that causes some instant feedback
- The result will be as shown in the picture attached 

![image](https://user-images.githubusercontent.com/42375494/201880714-54e614e0-0342-4e9d-b11a-900901b6c3df.png)

BR
Lassi Korhonen

**Comment by aharjula** [comment] 2022-11-15 10:34
Interesting, that translation should happen here:
https://github.com/maths/moodle-qtype_stack/blob/a55f392528cd146e872fddb4b1d731eba824dbd0/locallib.php#L148
Using the normal `get_string()` logic behind that `stack_string()` so the language selection should happen at the Moodle level. So it is interesting that Moodle would return different languages for different parts of *the page*.

*The page*, is the key here. The instant validation is not on the same page...

I guess this is because the instant validation does not actually set up the full context this happens... So apparently, the logic in the following function should somehow work up from the question attempt and identify the language override if any exists:
https://github.com/maths/moodle-qtype_stack/blob/a55f392528cd146e872fddb4b1d731eba824dbd0/classes/external.php#L70

One can probably assume that this has always been broken, i.e. we have always used the user global language setting, and that we need some Moodle trickery to figure out how we could identify the language override from the data we have available in that script.

Have to wonder whether it would be easier and faster to output the active language when rendering the question and pass that back via the validation request or if we should do the traversal of the database to find the overriding course when starting from a question attempt. It could be that traversal is slow, especially if we have to iterate all the way up to the root of the hierarchy if we can not see any overrides before that (assuming nested items respect parent item overrides).

**Comment by timhunt** [comment] 2022-12-06 23:14
The problem is that the web service used to validate the input just hard-codes the system context: https://github.com/maths/moodle-qtype_stack/blob/7f767ba08856c09fe02b6c5e6a3f72adcefa9bd4/classes/external.php#L79

I cannot see a way to get the right context id from the data available in that PHP function, so we probably need to add an extra argument here to pass it through. In the JS that calls this service, M.cfg.contextid is available.

**Comment by aharjula** [comment] 2023-08-29 07:34
@sangwinc This really should be solved in preparation for localised input. We really need the active locale both for parsing and this type of validation.

We need to store the active locale for all "steps" so that we can regrade them parsing with the same locale as they received the input in. And the easiest way to do this would be for each question (only those that have other inputs, no need for info-items) to have a hidden input that contains the pages active locale, that would be stored as a normal input value in the step-data and for this issue in particular would be passed to the instant validation with the JS-request, and could then be used to change the validation contexts locale/language and possibly parsing settings.

Note that Tim's above suggestion of passing the context id is not a safe solution as the context may change its locale/language at any point and we cannot later rely on it to have the same value as the student used when inputting anything.

**Comment by sangwinc** [comment] 2023-11-29 14:03
Relates issues are #940 and #1051.

**Comment by EJMFarrow** [comment] 2024-04-23 11:11
This should now be fixed in the next release. https://github.com/maths/moodle-qtype_stack/pull/1166

**Closed by EJMFarrow** 2024-04-23 11:11 UTC
Labels: Roadmap
