### ISSUE TITLE
replacedollars.php fails on certain contexts.

### ISSUE THREAD

**Issue by danmarsden** [maths/moodle-qtype_stack#335] opened 2017-12-14 19:32 UTC
Moodle 3.1 (latest stable)

The replace dollars script shows a number of items such as:
Quiz: XXX (10)
Quiz: YYY (12)
Course: ZZZ (19)

Hitting any of the "quiz" items in that list gets the error:
Coding error detected, it must be fixed by a programmer: The course you passed to $PAGE->set_cm does not correspond to the $cm.

I suspect it has something to do with the way the passed $context is used  - might need the system context to be set at the page level rather than using the $contextid being passed in the url.

full trace:
line 1023 of /lib/pagelib.php: coding_exception thrown
line 4033 of /lib/navigationlib.php: call to moodle_page->set_cm()
line 3537 of /lib/navigationlib.php: call to settings_navigation->load_module_settings()
line 724 of /lib/pagelib.php: call to settings_navigation->initialise()
line 773 of /lib/pagelib.php: call to moodle_page->magic_get_settingsnav()
line 3145 of /lib/navigationlib.php: call to moodle_page->__get()
line 3189 of /lib/navigationlib.php: call to navbar->has_items()
line 55 of /theme/bootstrapbase/renderers/core_renderer.php: call to navbar->get_items()
line 4265 of /lib/outputrenderers.php: call to theme_bootstrapbase_core_renderer->navbar()
line 60 of /theme/clean/layout/columns1.php: call to core_renderer->full_header()
line 1028 of /lib/outputrenderers.php: call to include()
line 958 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 1839 of /lib/setuplib.php: call to core_renderer->header()
line 56 of /question/type/stack/replacedollars.php: call to bootstrap_renderer->__call()

I haven't had a chance to look into this further yet but will let you know if I track the issue down further.

**Comment by sangwinc** [comment] 2017-12-15 09:23
Thank you, if you can track this down it would be a great help.

**Comment by timhunt** [comment] 2018-04-04 13:28
This is a duplicate of #322, which has more info, so closing this one.

**Closed by timhunt** 2018-04-04 13:28 UTC
