### ISSUE TITLE
Complex numbers and units

### ISSUE THREAD

**Issue by Famondir** [maths/moodle-qtype_stack#981] opened 2023-06-20 08:42 UTC
Hi all,
I'm just working on some exam questions and came across one odd issue again. Namely: STACK seems to be not able to have complex numbers passed to the `stackunits` function. There is no error but the teacher answer is not recognized as corrct by the system as well.

Therefore I often have to create two answer input fields or tell the students right ahead if the imaginary or the real part is expected by writing an imaginary unit character in front of the input fiel. E.g.:
![image](https://github.com/maths/moodle-qtype_stack/assets/43599267/3730870b-13bf-4a28-95df-8e3d9709586e)

It would be great if one was able to use complex numbers with units. Is there a work around? How do you design such questions UX?

Kind regards
Simon

**Comment by sangwinc** [comment] 2023-07-05 16:38
Simon,
Please could you provide some test-cases against which to work?  I'm sorry, but I'm not a physics teacher, and I've not had a need to apply units to complex quantities!  This sounds like a perfectly reasonable suggestion and I expect we can accommodate this.

If you type in `(1+2*i)*m/s` to a units input type then it correctly splits this into the number `1+2*%i` and the units `m/s`.  

Also, most of the numerical tests assume real numbers.  So, we'll need to give some careful thought to what you mean by two complex numbers, (probably written as floats?) being equal.

We'll need to do more design, but I expect this can be accommodated.
Chris

**Comment by sangwinc** [comment] 2023-07-06 12:05
Ok, I think this is relatively easy to fix.  By design (unwitting!) we're testing for a real number, e.g. here
https://github.com/maths/moodle-qtype_stack/blob/master/stack/maxima/stackunits.mac#L263
If we change these tests to be complex numbers then the code will split into complex numbers and units.  That's reasonably easy.

However, some users might be _relying_ on this behaviour and expect, by default, we're going to reject complex numbers.  This might be a very unwelcome change in existing behaviour.  I'd like to get some comments from other users on this issue before we just "fix this bug"!  It's clear we could add an option to support complex input if that's the right way to change things.

**Comment by sangwinc** [comment] 2023-07-06 12:17
Turning to the answer tests, these really do assume we have real numbers! 
The "UnitsRelative" answer test pulls the numerical check directly from ATNumRelative, e.g.
https://github.com/maths/moodle-qtype_stack/blob/master/stack/maxima/stackunits.mac#L510
This test rejects anything which is not a real floating point number.   I'll add a unit test to confirm this is the intended behaviour, and I don't think we should change it.

**Comment by sangwinc** [comment] 2023-07-06 12:25
In practical terms we don't have a ready-made answer test to deal with complex units.   I think you are going to need to test the properties you need in an indirect way.

Assume the student's answer (scientific units) is `ans1`, and the teacher's answer `tans`.  In the feedback variables, you could define
`float(abs(stack_units_nums(ans1)-stack_units_nums(tans)));`
This new variable be the absolute difference between the student and teacher's answer.  If you would accept compatible units then you'll need to convert both answers to base units first of course!
`float(abs(stack_units_nums(stack_unit_si_to_si_base(ans1))-stack_units_nums(stack_unit_si_to_si_base(tans))));`
Then you can check how close to zero this is.

**Comment by aharjula** [comment] 2023-07-06 12:28
Knowing nothing, but remembering something, I do believe that this requires new testing modes. While in some cases, one might be able to simply look at the absolute value of the difference between the TA and SA, I do believe that in various cases, one might be really interested in specific feedback, of the phase differences etc., and in those cases one could even expect exact values and not just floats. I.e. our current Units tests are very focused on decimal places and significant figures but when dealing with complex numbers those might not have any role, and the primary reason for the test becomes the automatic conversion to the same base units. It could also be that there are no numbers other than multipliers for some variables/constants in the answer at all and what we end up actually dealing with "AlgEquivalence + Unit conversion", with is basically the same as running `stack_unit_si_to_si_base()` for both sides of the AlgEquiv before comparison.

Whether ready-made tests can ever cover those cases is another matter. One will probably always need some preprocessing to divide the answer into suitable parts and test them with bespoke logic as predefining the roles of those parts might be pretty much impossible.

And this is not just about the answer tests. The input type itself needs to match the usage and the current Units input most certainly will have issues as it is pretty much focused on having a number multiplier for an unit. The algebraic input probably is better for this, but validation will get displayed differently and so on.

I would guess that Chris should probably search YouTube or some such for an introduction to complex numbers for electrical engineers to see what they deal with so that he could better understand the typical answers expected.

**Comment by sangwinc** [comment] 2023-07-06 12:37
Agreed Matti - I think we'll need new answer tests.  And I don't know what they are useful for, sorry!

**Comment by Famondir** [comment] 2023-07-06 13:00
Thank you for all your replies.

You are right avout the phase differences, Matt. Comparing the absolute values wouldn't be sufficient. In the courses I create STACK questions in for electrical engineers teachers they are fine with testing with the NumRelative or UnitesRelative (or the absolute variants). If the shift is pi/2 or within pi/2+-1% is not so crucial.

I think it would be totally find to split the number behind the scenes and test for real and imaginary part combined with given unit as I do. But it would be great if I dont have to create three input fields every time and to keep the feedback about the units. Otherwise I could switch to algebraic input and try to get the units (e.g. by extracting all non-constants and non-numbers somehow).

**Comment by aharjula** [comment] 2023-07-06 13:23
Indeed I imagine the input field type is the bigger issue here, after one has received the answer one can then split it into relevant parts and push those to sensible tests. But for now, I would imagine the biggest problems are related to the way one needs to wrap the complex number value in parenthesis and multiply that with the unit and that is probably very error-prone and validation is probably not helping at all. 

Obviously, the Units input type is doing something silly, and needs some work:
![Screenshot from 2023-07-06 16-18-40](https://github.com/maths/moodle-qtype_stack/assets/980957/ddbe48be-abdc-4117-862a-fe002fef3d5e)
*My understanding is that imaginary ohms are not simply negative ones and that validation display seems to have thought so. Also, what is the mystery unit in that list of units?*

I would imagine that even now you would not need three inputs though. Surely a single algebraic input for the complex number and another input for the unit would be enough, two is not optimal but it is less than three...

**Comment by aharjula** [comment] 2023-07-06 14:15
Worth noting that Maxima is perfectly happy to do the splitting of real and imaginary parts from a singular algebraic inputs value, but `stackunits_make` cannot deal with "constants" that are not "constant", which is not a problem if you just declare those constants.

```
(%i22) ans1:(2.2*%pi+1.2*%i)*V;
(%o22) (2.2*%pi+1.2*%i)*V
(%i23) realpart(ans1);
(%o23) 2.2*%pi*V
(%i24) imagpart(ans1);
(%o24) 1.2*V
(%i25) stackunits_make(realpart(ans1));
(%o25) stackunits(2.2*%pi,V)
(%i26) ans2:(2.2*const+1.2*%i)*V;
(%o26) V*(2.2*const+1.2*%i)
(%i27) stackunits_make(realpart(ans2));
(%o27) stackunits(2.2,V*const)   <<< suboptimal
(%i28) declare(const,constant);
(%o28) done
(%i29) stackunits_make(realpart(ans2));
(%o29) stackunits(2.2*const,V)   <<< looks better
```

**Comment by Famondir** [comment] 2023-07-06 15:16
Interesting.

**Comment by sangwinc** [comment] 2023-07-06 15:44
There are a lot of people pushing STACK in different directions, and for new subjects.  This is an important area - and we should support assessment in electrical engineering with complex numbers in these ways.  The question is, which bits should be in a question and which should be in the core?!   If you can identify really commonly used functions which you think should be in the core then please let us know.  E.g. "comparing two complex (float) numbers" should be in the core I think!  Currently we don't have functions for this, because complex numbers have really only been needed so far by pure mathematicians who want exact comparison....

**Comment by aharjula** [comment] 2023-07-07 06:34
Chris, this will also lead to some interesting problems with the unit system as it is. We might need to start thinking about what it should allow to be tuned and how rather soon. For example, these might be relevant:
 1. The definition of `Hz`could be something that needs to have an option to toggle what it means. Basically, #783 is still an issue and might be an issue here as well, although going for the complex numbers should side-step that nicely.
 2. We may need to provide means for checking whether an arbitrary expression with free variables is consistent in its use of units, i.e. are the units on both sides of an operator like `+` representing the same "dimension"? That kind of tool should probably have the option to give specific feedback specifying where the issue is in the expression, e.g. show the expression tree and where things get mixed up. This would naturally work for all dimensional analysis needs.
 3. The above one will require us to have the ability to declare the units for free variables. While the simple thing would be to simply set some `R:1*ohm` values during testing, it might be that at some point, we want to check things during validation and check the expression with assumptions about the units of `omega` etc. without actually setting any values for them. How that will happen and where is going to be interesting, but at least we now evaluate the whole question in the same CAS context and do not need to transfer the state of those declarations between initialisation, input-validation and PRT-evaluation.
 4. And we would really also need to have those general physics constants so that we could have units for them present in that analysis even if we would not write out the values.

**Comment by sangwinc** [comment] 2023-07-18 14:12
Ok, I've merged this into dev.  We now accept complex numbers as units.  If people want to restrict this we can use bespoke validation to reject complex numbers.

**Comment by sangwinc** [comment] 2023-07-18 14:13
We still need to think about answer tests for this application though!

**Closed by sangwinc** 2023-07-18 14:12 UTC
