### ISSUE TITLE
Feature request: Drawing, Sketching

### ISSUE THREAD

**Issue by ttxtea** [maths/moodle-qtype_stack#602] opened 2020-07-01 13:38 UTC
For some mathematical exams some way to input a wide variety of graphs, sketches would be much appreciated. I have no really good suggestion for how to do that though.

**Comment by sangwinc** [comment] 2020-07-01 19:17
Thanks for suggesting this.  This is a duplicate of issue #565!

**Closed by sangwinc** 2020-07-01 19:17 UTC
