### ISSUE TITLE
Just for information... PHP max_input_vars default value..

### ISSUE THREAD

**Issue by aharjula** [maths/moodle-qtype_stack#207] opened 2016-05-12 12:39 UTC
Slightly interesting thing happened today when an author added the 33rd prt node to a question having 5 prts and 5 inputs, this led to the editing form having too many input fields for Ubuntus default PHP-settings and caused hilarious symptoms with the node graphs.

Maybe someone should note that you may need to increase this value in your servers php.ini if you wish to push your STACK to the limits.

Also same problem happens much earlier if you use WYSIWYG editors as they may add additional inputs.

**Comment by timhunt** [comment] 2016-05-12 15:21
I thought that Moodle had code in place to get around PHP's POST limit.

See https://tracker.moodle.org/browse/MDL-41451 and https://tracker.moodle.org/browse/MDL-52226.

The second of those fixes only went into Moodle 2.9.4 and 3.0.2. I wonder if the problem is that you are running an older version of Moodle?

**Comment by aharjula** [comment] 2016-05-13 06:22
Yes an older Moodle, which is not that uncommon as not everyone can request updates for Moodle installs when there are large scale customisations and custom plugins involved. Anyway people with my kind of a problem where they can't upgrade the Moodle just now can still probably increase that PHP-var. Plenty of 2.8 installs around still.

In any case if some future problem presents as an inability to add new nodes causing duplicate similarly named nodes popping up with broken connections or if the texts of various castext fields start to wander around the question from field to field overwriting and duplicating content when using WYSIWYG text editors then you most likely have this problem and should try if increasing that limit helps.

Not really a STACK problem but does present itself in interesting ways with STACK.

2.9.3 naturally did not work, but 2.9.6 did so there is a fix there indeed.

**Comment by sangwinc** [comment] 2016-06-10 10:25
Tim, Matti,
I'm reviewing older issues.  Should we close this or do something to STACK?!  I'm not sure how to proceed with this one.

**Comment by aharjula** [comment] 2016-06-10 10:27
Exist just to document an issue that has nothing to do with STACK. Can easily do that even when closed.

**Comment by timhunt** [comment] 2016-06-10 10:28
Agreed. Closing.

**Closed by timhunt** 2016-06-10 10:28 UTC
