### ISSUE TITLE
Matrix answer invalid for any input

### ISSUE THREAD

**Issue by vohonen** [maths/moodle-qtype_stack#1306] opened 2024-11-12 10:39 UTC
I'm a head TA at a Matrix Algebra course that runs on the MyCourses platform and has a STACK question on matrix multiplication. I could see from the question settings that the question was made in 2015 and has been assumedly used in each yearly course iteration since. I certified from last year's head TA that there was no issue in the previous iteration. However, this time the question throws an error message that the input is invalid:

![Screenshot from 2024-11-12 12-27-16](https://github.com/user-attachments/assets/14f9f499-e693-4cbe-9103-4044a97d6529)

Again, this was working at least last year and assumedly for almost ten years. A similar question with matrix multiplication on the same quiz with similar options works without throwing an error.  In that subsequent question, the text after the answer "Your last answer was interpreted as follows: matrix([37,47],[27,20],[55,24])" formats the matrix in TeX fashion. The input type and answer is obviously a matrix for both questions. 

I cannot infer much from the [docs](https://docs.stack-assessment.org/en/Authoring/Inputs/#matrix) because they don't mention this kind of behaviour for a matrix input. Any help on how to proceed?

**Comment by sangwinc** [comment] 2024-11-12 10:47
OK, if you email me the question to C.J.Sangwin@ed.ac.uk, and confirm which version of STACK you're running, I'll take a look.
Chris

**Comment by aharjula** [comment] 2024-11-12 11:26
Chris,

This is a thing related to forbidden words that broke in last summers update, and does not seem to propagate fast enough through our course staff...

I think there is an issue already, but cannot at this moment remember it. In any case, previously one could have `matrix` as a forbidden word for a matrix input to stop anyone doing stuff with matrices inside the cells of that input, now however, the forbidden words are not applied cell by cell but instead on the whole input value which is obviously a matrix and thus always invalid if one has that forbidden word defined.

**Comment by sangwinc** [comment] 2024-11-12 12:06
@vohonen thanks for emailing me your question.  In that question you don't have "matrix" in the forbidden words for the input, so I don't think that's the problem.

I can't reproduce the invalidity, so I'm not sure what's going on with this.

(Also, just a reminder. Please could you add question tests and deploy variants?  https://docs.stack-assessment.org/en/Authoring/Deploying/ It makes tracking down problems a lot easier.)

**Comment by aharjula** [comment] 2024-11-12 14:20
Chris,

Had a chat with the reportter, they managed to fix the question by removing the forbidden word and did not notice that they were testing still with the old version thus sending you the fixed one, Moodle and versions is too easy. In any case, this is a real issue and affects many old materials and did indeed crop up this summer.

Here is a minimal question, simply a matrix input with `matrix` in the forbidden variables, fails with about week old dev:

[Matrix forbidden-words.xml.txt](https://github.com/user-attachments/files/17717817/Matrix.forbidden-words.xml.txt)

**Comment by sangwinc** [comment] 2024-11-13 11:45
Thanks @aharjula, let's try to get a fix for this into the next release.  I'll have a look.

**Closed** 2024-11-13 17:05 UTC
Labels: Bug report
