### ISSUE TITLE
STACK 4: fill in correct response button

### ISSUE THREAD

**Issue by ianjones** [maths/moodle-qtype_stack#394] opened 2018-08-01 08:12 UTC
Since I upgraded to Moodle 3.4 and STACK 4.x the "fill in correct response" button does nothing. I wondered if anyone has any suggestions.

**Comment by ianjones** [comment] 2018-08-02 11:43
Thanks Chris, that's very much appreciated. 

Our IT person (you'll recall Rich Goodman) is away until Monday, so I can't be sure the exact version number of either STACK or Moodle until then. Also, I received an automatic email alerting me to a plugin that I know hasn't been updated yet "STACK (qtype_stack) There is a new version 2018073000 available!"

So rather than bother you further right now I'll wait until Monday, ask Rich to update everything, and then check where we are.

Have a good weekend.

**Comment by ianjones** [comment] 2018-08-07 08:35
Here's the details:  Moodle 3.4.3 and Stack 4.1 for Moodle 2.7+ (2017121800)

Ian

**Comment by sangwinc** [comment] 2018-08-11 06:40
Ok Ian,
I think the problem is fixed on 4.2.  Please could you email me one affected question and I'll confirm? (Or I'll fix it!)

**Comment by ianjones** [comment] 2018-08-13 11:12
Thanks Chris. Here's an example, but it seems to be all questions in terms of the "Fill in correct responses" button not working. 


[questions-15MAZSTACK-Business school examples-20180813-1210.xml.zip](https://github.com/maths/moodle-qtype_stack/files/2282728/questions-15MAZSTACK-Business.school.examples-20180813-1210.xml.zip)

**Comment by sangwinc** [comment] 2018-08-13 12:01
Ian, the "Fill in correct responses" is working on the current version (4.2.1).

**Closed** 2018-08-20 09:57 UTC

**Comment by ianjones** [comment] 2018-08-29 08:34
"Fill in correct responses" continues not to work I'm afraid. I just got the updates status from Richard Goodman in ITS:

STACK
qtype_stack
4.2.1 for Moodle 3.0+
2018080600

Adaptive mode (multi-part questions)
qbehaviour_adaptivemultipart
4.2.1 for Moodle 3.0+
2018080600

Deferred feedback with CBM and explicit validation
qbehaviour_dfcbmexplicitvaildate
4.2.1 for Moodle 3.0+
2018080600

Deferred feedback with explicit validation
qbehaviour_dfexplicitvaildate
4.2.1 for Moodle 3.0+
2018080600

**Comment by aharjula** [comment] 2018-08-29 09:27
Cannot reproduce the issue here either... Could it be some custom theme in the Moodle doing something to the buttons but not for that button? 

Does the button work for non STACK questions? Just checking as that button is more part of Moodle than STACK although STACK does supply the values for it to do its thing.

Also is it certain that the question behaviour selected in the question preview is one of those that STACK supports and not some new and exotic one? There exists others that have "Adaptive" in their name...

**Comment by ianjones** [comment] 2018-08-30 07:44
Thank you Matti. I've looked into that it it's only STACK question types that the buttons aren't working for, and I the question behaviour doesn't look exotic to me. However I have emailed the generic Moodle people at my university to ask for any suggestions as to what might be wrong with the STACK questions. Maybe there's some other generic Moodle setting I'm missing.

**Comment by ianjones** [comment] 2018-08-30 13:03
A response from the Moodle person, I'm feeling a bit stuck.

"The question preview is a Moodle function that is the same for each question previewed, so some of the behaviours won't be applicable to the STACK question type.

I'm guessing that an internal Moodle change has broken this, and probably the best person to discuss this with is Chris, as he is probably already aware of this and might even have a solution?"

**Comment by aharjula** [comment] 2018-08-30 13:27
Well Chris is probably aware of this but as long as we are unable to replicate the issue we are unable to find what actually is broken. As said I cannot replicate it and I have tried a few different Moodle & STACK combinations and I assume Chris was also unable to replicate it. 

We must assume that the problem is with some very specific combination of versions in your Moodle and to find the issue we would need to know all the versions of all the plugins installed into it and the version of PHP and even the database used to try to duplicate the whole situation. Basically, what do these pages in your Moodle say "/admin/environment.php" & "/admin/plugins.php?&contribonly=1"? Might be simpler to just sanitise (there are details there that you do not want to share) the config.php and zip up the whole Moodle-dir and pass that zip to us for testing.

You should also clear the CAS cache and check that all is fine here "/question/type/stack/healthcheck.php"...

**Comment by ianjones** [comment] 2018-09-02 07:49
I very much appreciate the trouble you are taking to help me sort this out. I requested the information from IT and here is what they have replied with.
Ian

[serverchecks.pdf](https://github.com/maths/moodle-qtype_stack/files/2343057/serverchecks.pdf)
[questiontypesANDbehaviours.pdf](https://github.com/maths/moodle-qtype_stack/files/2343058/questiontypesANDbehaviours.pdf)

**Comment by aharjula** [comment] 2018-09-03 05:40
Well I'll try to build a similar installation but new students just entered the campus so it will probably take couple of days.

**Comment by ianjones** [comment] 2018-09-03 08:09
Thank you so much, really appreciate this. Ian

**Comment by aharjula** [comment] 2018-09-04 09:00
Still no reproduction, all the plugins and Moodle with those versions and even PHP nearly matching (7.1.20 vs 7.1.18) and still it works. Both with local and Pool maxima. As reproduction based on high level details is not giving results I believe that this should be explored in the system where it is present, i.e. turn on all the debug output in that Moodle and check the logs if anything funny appears and if that does not give anything start placing additional logging along the code path of that button.

However, I would first check that the executing environment is fully functional and that the code it executes is intact. Starting to think that a cosmic ray hitting the scripts of STACK on that particular system might explain things.

If you still wish me to continue to try to reproduce this I would need the full description of the server. Starting with the distribution and version of the operating system, and the configuration of PHP serving in the web server e.g. are there any caches or accelerators in that chain.
