### ISSUE TITLE
Pedantic display: Variable matrix and compact validation

### ISSUE THREAD

**Issue by timlowe** [maths/moodle-qtype_stack#1058] opened 2023-11-13 15:31 UTC
Hi,

When using "variable matrix" input and compact validation, the validation does not  nicely align with the input field. (It does align for fixed-size matrix.) See attached.

Also, can the matrix input be made to appear inline with the preceding text (as it does for numerical entry)? 
The question code has  \( \mathbf{A} = \) [[input: ans1]], but the preview shows a line break.

(I realise this is pedantic - just trying to make the question look appealing!)

Tim

![variable matrix](https://github.com/maths/moodle-qtype_stack/assets/5654528/ca399336-7477-4f89-8eab-c1fb3877d05a)

**Comment by LukeLongworth** [comment] 2023-11-13 17:31
Ah, we have had this problem too. My modern fix is to put the A= and the input into adjacent cells of a table without borders, but this isn't particularly elegant. 

If I'm remembering correctly, this is (partially) mitigated if you don't put this in <p> tags. When the question page is generated I think it inserts some of its own <p> tags which causes the line break. My earlier fix for this problem was putting it all in a <span> tag. Note: I am not a developer and this was a while ago!

**Comment by georgekinnear** [comment] 2023-11-14 13:40
I think I've seen this issue before too - the solution is to edit your HTML so that the "A = ..." is in a `<div>` rather than a `<p>`.

(The issue is with HTML, where "display" objects cannot appear inside "inline" objects - the matrix input is a "display" object so it cannot sit inside a `<p>` which is an "inline" object: https://stackoverflow.com/questions/8397852/why-cant-the-p-tag-contain-a-div-tag-inside-it)

**Comment by timlowe** [comment] 2023-11-14 15:33
Thanks George! Yes, using <div> overcomes the line-break issue. but the misaligned compact verification feedback remains!

(Luke  - I'd rather not use a table, as that makes life difficult for screen-reader users!)

**Comment by georgekinnear** [comment] 2023-11-14 15:50
I'm not sure if there's a better way other than to put the `[[validation:ans1]]` tag inside a `<div>` that you tweak to get it in the right position - e.g.

```
<div>\(A=\) [[input:ans1]]
    <div style="display: inline-block; vertical-align: top;">[[validation:ans1]]</div>
</div>
```

That's still not perfect, so you maybe want to add `margin-top: 0.2 em` to the style (but you could spend forever tweaking that number to make it line up perfectly, I fear!)

**Comment by sangwinc** [comment] 2024-03-26 14:49
George, are you suggesting we add this <div> style round the validation message as a default?  If so, what happens to people who've also added it manually as you suggest above?

**Comment by georgekinnear** [comment] 2024-03-26 17:47
I'm always reluctant to propose changes to the CSS - as you suggest, any changes might have unwanted implications for some people.

But having looked a bit more at this, I think adding `vertical-align: top` to both the compact validation and prt styling would be helpful.

For the question that I showed at the STACK conference, the current default behaviour is not great! Here's a snippet of the question text and a screenshot of what happens once the feedback is filled in:

```
<div id="eigenvalues_part1">
<p>Give an example of a matrix with eigenvalues 1 and 5. </p>
<p>[[input:ans1]] [[validation:ans1]] [[feedback:prt1]]</p>
</div>

<div id="eigenvalues_part2">
<p>Give an example of a matrix with eigenvalues 1 and 5, that is not diagonal. If no such example exists, enter none.</p>
<p>[[input:ans2]] [[validation:ans2]] [[feedback:prt2]]</p>
</div>
```
![image](https://github.com/maths/moodle-qtype_stack/assets/30723394/5c55d3cb-d926-4bba-beb3-775a94004dba)

Tweaking the CSS to add `vertical-align: top` to both `.que.stack .stackinputfeedback.compact` and `.que.stack .formulation .stackprtfeedback` gives:
![image](https://github.com/maths/moodle-qtype_stack/assets/30723394/013f673e-29c7-45a6-a238-11d228cd0ad7)

It has no effect on the appearance of the workaround that I posted above.

**Comment by timlowe** [comment] 2024-03-26 17:52
For what its worth, I'm of the opinion that the system should align things nicely by default, and not require the user to tinker with HTML/CSS alignment in each individual question.

George's suggestion of `vertical-align:top` sounds good to me.

**Comment by sangwinc** [comment] 2024-03-26 18:31
@georgekinnear CSS is one area where you are considerably more competent than me, and your suggestions are very welcome.  Thanks.

**Closed** 2024-03-26 18:57 UTC
