### ISSUE TITLE
Translation issue with tags

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#170] opened 2016-01-16 20:14 UTC
Hi! Since updating to Moodle 3.0 and the Abacus branch of STACK, I have a translation problem that I cannot locate. Can you perhaps help? 

In the Finland-Swedish translation, I cannot enter any tags:
![sv_fi](https://cloud.githubusercontent.com/assets/1645276/12374254/5425655c-bc9e-11e5-968d-3850b7ddc655.png)

In the English and Finnish translations, there is no problem:
![fi](https://cloud.githubusercontent.com/assets/1645276/12374258/60dc72e0-bc9e-11e5-88e0-6c6df056a3aa.png)

Thanks for any help!

**Comment by lentzi90** [comment] 2016-01-30 08:22
The same thing happens after editing the tags and saving the changes with the English version:
![stack_tags_missing](https://cloud.githubusercontent.com/assets/9117693/12694606/52c76d3e-c73b-11e5-84f8-b59b2ddc4f83.png)

**Comment by timhunt** [comment] 2016-01-30 08:26
The tag editing interface for questions is a standard part of Moodle. You need to report this bug at https://tracker.moodle.org/. I doubt the problem is STACK-specific.

I will close this.

**Closed by timhunt** 2016-01-30 08:26 UTC

**Comment by alcarola** [comment] 2016-11-14 10:04
Just for documentation: Indeed, I can now confirm that the same problem shows upp in the Calculated multiple choice question type.
