### ISSUE TITLE
Exception: property_exists(): Argument #1 ($object_or_class) must be of type object|string, null given

### ISSUE THREAD

**Issue by alcarola** [maths/moodle-qtype_stack#965] opened 2023-05-29 18:54 UTC
Hi, I'm trying to add a PRT to the attached question, in order to provide some feedback on answer 5, but I only keep getting the following exception:

property_exists(): Argument #1 ($object_or_class) must be of type object|string, null given

STACK: $plugin->version   = 2022082900;
Moodle 4.2+ (Build: 20230526) | Version 2023042400.05

[frågor-Talteori-Standard för Talteori-20230529-2148.xml.zip](https://github.com/maths/moodle-qtype_stack/files/11593696/fragor-Talteori-Standard.for.Talteori-20230529-2148.xml.zip)

**Comment by sangwinc** [comment] 2023-05-30 05:12
I'm very sorry about this error.  This is a duplicate of issue #963, and I'm confident it has been fixed in the latest release.
Chris

**Comment by sangwinc** [comment] 2023-05-31 06:51
I'm very sorry if this hasn't been fixed!  Please could you email me (1) the whole error message (it has line numbers in the code) and (2) the question .xml which generated it. 

The previous issues were caused by changes in PHP 8.0 and 8.1 which now no-longer accept "null" in place of an empty string in some functions.  This is proving hard to track down, but we will be able to fix this.

**Comment by alcarola** [comment] 2023-05-31 09:15
The latest version of the question is attached here, and this is the debug output:

Exception - property_exists(): Argument #1 ($object_or_class) must be of type object|string, null given

[More information about this error](http://docs.moodle.org/401/en/error/moodle/generalexceptionmessage)

Debug info:
Error code: generalexceptionmessage×Dismiss this notification
Stack trace:
line 85 of /question/type/stack/stack/prt.class.php: TypeError thrown
line 85 of /question/type/stack/stack/prt.class.php: call to property_exists()
line 518 of /question/type/stack/questiontype.php: call to stack_potentialresponse_tree_lite->__construct()
line 965 of /question/type/questiontypebase.php: call to qtype_stack->initialise_question_instance()
line 288 of /question/engine/bank.php: call to question_type->make_question()
line 278 of /question/engine/bank.php: call to question_bank::make_question()
line 217 of /question/bank/editquestion/question.php: call to question_bank::load_question()
×Dismiss this notification
Output buffer: <br /> <b>Warning</b>: Undefined array key "prt5" in <b>/var/www/html/moodle/question/type/stack/questiontype.php</b> on line <b>516</b><br /> <br /> <b>Warning</b>: Attempt to read property "value" on null in <b>/var/www/html/moodle/question/type/stack/questiontype.php</b> on line <b>516</b><br /> <br /> <b>Warning</b>: Undefined array key "prt5" in <b>/var/www/html/moodle/question/type/stack/questiontype.php</b> on line <b>518</b><br /> <br /> <b>Warning</b>: Attempt to read property "name" on null in <b>/var/www/html/moodle/question/type/stack/stack/prt.class.php</b> on line <b>76</b><br /> <br /> <b>Warning</b>: Attempt to read property "autosimplify" on null in <b>/var/www/html/moodle/question/type/stack/stack/prt.class.php</b> on line <b>77</b><br /> <br /> <b>Warning</b>: Attempt to read property "feedbackstyle" on null in <b>/var/www/html/moodle/question/type/stack/stack/prt.class.php</b> on line <b>78</b><br /> <br /> <b>Warning</b>: Attempt to read property "feedbackvariables" on null in <b>/var/www/html/moodle/question/type/stack/stack/prt.class.php</b> on line <b>83</b><br />

[questions-Talteori-Del 1 Diofantisk ekvation 2-20230531-1214.xml.zip](https://github.com/maths/moodle-qtype_stack/files/11610968/questions-Talteori-Del.1.Diofantisk.ekvation.2-20230531-1214.xml.zip)

**Comment by sangwinc** [comment] 2023-05-31 16:14
Well, I'm very sorry about this.  I can't reproduce the problem.  Can I ask, did you delete prt5 at any point and then try to add it back in?  Can you add in any other PRTs (as an experiment?).

I have to confess, I'm not using Moodle 4.2 yet.  That could be the issue.

**Comment by sangwinc** [comment] 2023-06-01 13:29
Thanks to everyone for helping me track this down.  I don't know why Moodle 4 has changed behaviour here, but I did reproduce this problem and I'm confident the original problem is now fixed.

Chris

**Comment by sangwinc** [comment] 2023-06-01 18:48
As soon as we are absolutely sure this, and any similar problems, are fixed I will release an official bug fix version.  I always used the "update form" button rather than save.  I don't completely understand the changes in Moodle which now created this problem, but there is certainly a difference between the "update form" button and "save and continue" which I didn't spot, so very sorry for that.

If you are able to use "dev" for testing and to help sort this out, your help would be appreciated. Otherwise, I'll release this fix as a new STACK release in due course - certainly in time for Edinburgh to use it during 2023-24!

Chris

**Comment by alcarola** [comment] 2023-06-02 05:13
OK, thanks! I do not have a test server, and I am a bit wary of experimenting with my production server. We still have exams next week, which may use STACK. 

In any case, is it always possible to switch back master branch if I change to the dev branch, or does the moodle database prevent that?

I tried both the "update form" and "save question" ways, but it did not matter which one I used. The exception showed up at the point where I tried to save the question; updating the form worked fine.

**Comment by tlock** [comment] 2023-06-05 03:43
We are using 4.4.1 and trying to patching accordingly, ignored the add_prt_node() change as class doesn't have that function yet. Works otherwise.

**Comment by sangwinc** [comment] 2023-06-05 06:47
Sorry, I don't understand this comment "ignored the add_prt_node() change as class doesn't have that function yet".  I think we need to add nodes as prt_nodes from the get-go to make sure we have the additional fields expected in the newer text-view.

**Comment by aharjula** [comment] 2023-06-05 06:51
Well, patching 4.4.1 with features related to the PRT-graph rendering/handling refactor present in 4.4.3+ might get messy. I would assume that is the reason for that comment.

**Comment by sangwinc** [comment] 2023-06-05 06:55
Argh yes, so this is patching an older system not upgrading.  I'm about to release 4.4.4 as a bug fix release to fix this issue and #965.  I'm still testing this to make sure we've really fixed all these notices.

**Comment by sangwinc** [comment] 2023-06-05 10:58
This is fixed in STACK 4.4.4.

**Closed by sangwinc** 2023-06-05 10:58 UTC

**Comment by alcarola** [comment] 2023-06-05 21:29
I can confirm that the original issue has now been resolved for me, after I did a git pull on the master branch of STACK today.

**Comment by sangwinc** [comment] 2023-06-06 05:42
That's good to know, thanks for confirming.  I'm sorry about the original problem.  Thanks for your patience.
