### ISSUE TITLE
Reveal block

### ISSUE THREAD

**Issue by malthefogsporring** [maths/moodle-qtype_stack#1023] opened 2023-09-15 08:33 UTC
When trying to make a simple question with the reveal block on the stack-demo server, I'm getting the following error:

'Exception - Return value of stack_cas_castext2_special_root::make() must be an instance of stack_cas_castext2_block, instance of stdClass returned'

Is this replicable by others?

--

The issue I actually wanted to report was that when multiple questions using reveal blocks referring to the same variable are on the same page of a quiz, only the first question's reveal block will work. However, the above issue means I can't confirm that the issue persists on the newest version of STACK.

**Comment by aharjula** [comment] 2023-09-15 08:57
I wonder what version of STACK that server is running.

In any case, #969 should already be fixed. It may not have been released yet though. Should have been but who knows.

**Comment by sangwinc** [comment] 2023-09-15 09:01
@malthefogsporring if you drop me an Edinburgh email with more details then I'll look into it and we can get this fixed.

**Comment by aharjula** [comment] 2023-09-15 09:03
@sangwinc The problem is simple:

"Your site is running STACK version 2023010400 (descriptive, distrib, simplex, stats)."

**Comment by sangwinc** [comment] 2023-09-15 10:52
That would do it!  We need to update our public demo site...

**Comment by sangwinc** [comment] 2023-09-15 10:58
Thanks for reporting this @malthefogsporring, much appreciated.  The fix is included in the latest version of STACK.

**Closed by sangwinc** 2023-09-15 10:58 UTC
