### ISSUE TITLE
String values inserted into TeX expressions need to be wrapped in {}

### ISSUE THREAD

**Issue by timhunt** [maths/moodle-qtype_stack#407] opened 2018-10-10 14:44 UTC
When inserting string values into TeX (not recommeded, but some old questions do it, preceding the built in number formatting options for things like decimal places) then it broke. Minimal example to reproduce:

```
\(\frac{@"0.10"@}{@"0.10"@}\)
```

It took a while to work out the real cause. Original, slighly erroneous description follows:

If, before moving to STACK 4.x, your question text / feedback contained something like

 \frac{@a@}{@b@}

then really that needs to have been updated to 

 \frac{{@a@}}{{@b@}}

but, the replacedollars.php script did not do that! Ouch!

**Comment by aharjula** [comment] 2018-10-10 15:01
Tim, if that is the exact situation then it works perfectly, the new `{@a@}` leads to output of `{a}` (+ the math mode wrapping if need be) i.e. it does not eat the braces thus that `\frac` does not need them to be duplicated. It does however do this` \frac{@A@+1}{@b@}` => `\frac{{@A@}+1}{@b@}` i.e. it knows when they are needed and tries to save pointless extra chars.

Problem is that if you had something like this `\(blaah^@1+x@\)` => `\(blaah^1+x\)` in that case the fixer should give you `\(blaah^{@1+x@}\)` which has very different output `\(blaah^{1+x}\)`. This however is an intentional change as typically this case in unintended error by the author.

**Comment by aharjula** [comment] 2018-10-10 15:08
Just in case it might interest someone `{#a#}` => `a` does eat the braces as it is not intended to be used for generating LaTeX where the braces are and can be used as non visible grouping.

**Comment by timhunt** [comment] 2018-10-10 15:14
Thank you for the speedy response.

OK, good, the simple \frac{@A@}{@b@} case does not break. I just simplified it to try to make the bug report easier to read.

An example of a real broken case from one of our questions is:

So to 2 s.f., the Dogger Bank earthquake was \(\displaystyle\frac{@toSciCond(ad)@}{@toSciCond(al)@}={@f@}\) times more severe than the Lincolnshire incident.

which is leading to the TeX

\displaystyle\frac\displaystyle 1.58489319246\times 10^{25}\displaystyle 5.01187233627\times 10^{23}={32}

which definitely does not render correctly. Any advice?

**Comment by timhunt** [comment] 2018-10-10 15:27
Note that manually editing this question to

```
... \(\displaystyle\frac{{@toSciCond(ad)@}}{{@toSciCond(al)@}}={@f@}\) ...
```

Fixes the display.

**Comment by aharjula** [comment] 2018-10-10 15:44
Ok. So I think that this is related to something that was created in some Chris's dev branch before abacus got merged and was directly implemented to STACK4 and I cannot find the actual commit it is based on. What happens is the [here](https://github.com/maths/moodle-qtype_stack/blob/master/stack/cas/castext/latex.block.php#L67) we react to the value being string by writing it out as is and as that is what is wanted we do not output those braces. The replace dollars obviously does not know that this could happen and therefore it does not know to add double braces there. So yes it should have added the braces here but in general it looks better not to add them. Depending on how large the set of questions you have to fix you might want to change the regex in the replace dollars to not save braces or just fix by hand.

**Comment by timhunt** [comment] 2018-10-10 16:14
Thanks. That makes sense. At first, I was panicking, because it seemed like all \frac{@A@}... was affected, which was ~1500 questions.

Now it is just string things, that is less bad, though I am still struggling to get a handle on it.

Hmm. Looks like toSFStr etc. are functions our question authors have defined and copied and pasted into many questions. Yuck!

**Comment by aharjula** [comment] 2018-10-10 16:56
I don't really have anything against that. People really should not mix math mode and strings but maybe we can adapt the string logic to help when that happens.

**Comment by timhunt** [comment] 2018-10-10 17:04
Indeed, the STACK equivalent

\(\frac{@dispdp(0.1, 2)@}{@dispdp(0.2, 2)@}\)

works fine. It is only our old in-house display functions like toSFStr that break. They return strings, which triggers this bug.

**Comment by timhunt** [comment] 2018-10-10 18:12
OK, I made pull request #408 for this. That adds a unit tests, fixes the one other unit test that needs fixing, and cleans up the git history.

Without the change, the new unit test fails with

```
1) stack_cas_text_test::test_basic_castext_instantiation
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'\(\frac{0.10}{0.10}\)'
+'\(\frac0.100.10\)'

C:\Users\tjh238\workspace\ouvle2\question\type\stack\tests\castext_test.php:46
C:\Users\tjh238\workspace\ouvle2\question\type\stack\tests\castext_test.php:77
C:\Users\tjh238\workspace\ouvle2\lib\phpunit\classes\advanced_testcase.php:80

To re-run:
 vendor/bin/phpunit "stack_cas_text_test" question/type/stack/tests/castext_test.php
```

Is it OK for me to merge this to master?

**Comment by aharjula** [comment] 2018-10-11 05:57
Well, I don't really know if we want it but I see no major reason why we should not have it, Chris can decide. My view is:
 1. Restores a technical feature to previous functionality.
 2. However using that feature is not something we would recommend as we provide cleaner and system level identifiable ways for generating presentation for numbers in most cases.
 3. I cannot come up with an example I would have seen where this logic change would break things but in theory it is possible although probably even less common than the cases this fixes.

Only reason I can come up against it is my vision of Maxima evaluated CASText rendering where I would need to build one more if in some small subbranch in my compiler (CASText string => Maxima expression compilation). But that is not an issue. That is far into the future of single Maxima call PRT evaluation with feedback generation in the same call.

**Comment by timhunt** [comment] 2018-10-12 13:17
Thanks for all you help with this Matti. I wonder where Chris is. Unlike him not to comment sooner. I hope he is away somewhere interesting and/or fun.

I will wait before adding this ot STACK/master. However, just for info, I am going to go ahead an patch this fix onto the OU's live servers.

**Comment by sangwinc** [comment] 2018-10-12 13:20
Sorry folks, just a bit snowed under with traditional face to face teaching!  Nowhere exotic!

**Comment by sangwinc** [comment] 2018-10-14 13:58
Thanks Tim, Matti for looking at this.

I'm happy with this proposed fix.  

My only suggestion before we merge the changes and ignore the problem is to weed out the use of these legacy functions by adding in a check here (https://github.com/maths/moodle-qtype_stack/blob/master/question.php#L997) with a suitable supported current alternative?

Chris

**Comment by timhunt** [comment] 2018-10-14 15:10
Thanks Chris.

The only legacy maths functions here are ones that OU question authors have defined in the question variables of their own questions. So, I am not really sure what checks could usefully be added to STACK itself.

**Comment by sangwinc** [comment] 2018-10-14 17:43
Tim,
If authors are regularly adding functions to numerous questions then there is a very good case for us to add that functionality to the core.  If they are working parallel to core functionality we've provided in a different way, we should weed it out!  These are private OU questions of course (!) but don't hesitate to say "we are doing this regularly and it should be a supported feature" if it helps.

**Comment by timhunt** [comment] 2018-10-14 21:03
Indeed. These were numerical rounding functions, which did get into STACK. Unfortunately, there has not been time since the new STACK features were added to update all our old questions.

**Closed** 2018-11-01 17:57 UTC
