### ISSUE TITLE
PHP 8.0 parameter order deprecations

### ISSUE THREAD

**Issue by thepurpleblob** [maths/moodle-qtype_stack#839] opened 2022-08-18 14:08 UTC
A number of "required parameter XXX follows optional parameter YYY" deprecation warnings. In lines...

https://github.com/maths/moodle-qtype_stack/blob/155802c9b4ca6864171db931ce1ef9eb35961efd/stack/cas/castext2/block.interface.php#L99

https://github.com/maths/moodle-qtype_stack/blob/155802c9b4ca6864171db931ce1ef9eb35961efd/stack/cas/castext2/blocks/commonstring.block.php#L121

https://github.com/maths/moodle-qtype_stack/blob/155802c9b4ca6864171db931ce1ef9eb35961efd/stack/cas/castext2/blocks/textdownload.block.php#L82

https://github.com/maths/moodle-qtype_stack/blob/155802c9b4ca6864171db931ce1ef9eb35961efd/stack/cas/castext2/blocks/include.block.php#L90

**Comment by sangwinc** [comment] 2022-08-18 14:22
Thanks for raising this - this issue is a duplicate of issue #818 and I think is now closed.

**Comment by timhunt** [comment] 2022-08-22 13:06
This was a duplciate, but CAStext 2 added new instances. I will fix.

**Comment by timhunt** [comment] 2022-08-22 13:10
Ah! the sepcific ones here were fixed, but there was at laest on new one:

Deprecated: Required parameter $statics follows optional parameter $weight in /var/www/html/moodle/question/type/stack/stack/prt.evaluatable.class.php on line 68

which I am just fixed.

Please can we setop adding these.

**Closed** 2022-08-22 14:11 UTC
