### ISSUE TITLE
stack bug

### ISSUE THREAD

**Issue by AmirGurion** [maths/moodle-qtype_stack#522] opened 2019-11-16 02:42 UTC
when my students write an answer to an inqualety and use the words "and"/"or", the validation disapear. 
this is how I see there answer:
<img width="680" alt="ככה אני רואה" src="https://user-images.githubusercontent.com/57820474/68986761-4c017000-082b-11ea-8372-105810a86428.png">
and this is what few of the students sees:
![ככה התלמיד רואה](https://user-images.githubusercontent.com/57820474/68986767-650a2100-082b-11ea-80fb-598473fd523d.jpg)

**Comment by sangwinc** [comment] 2019-11-20 13:26
Sorry about this, it is odd and I can't reproduce it.
(1) Which version of STACK are you using (see here: https://github.com/maths/moodle-qtype_stack/blob/master/version.php on your system, reproduced on the front page of the docs)
(2) Is this in Hebrew only or does this problem also occur in English?

**Comment by AmirGurion** [comment] 2019-11-20 17:27
thank you for your response.
our site is running STACK version 2017121800.
I'll try to find if it happened in english.

‫בתאריך יום ד׳, 20 בנוב׳ 2019 ב-15:26 מאת ‪Chris Sangwin‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by sangwinc** [comment] 2020-04-03 13:30
I can't reproduce this issue, either in English or Hebrew.  So, I'm going to close the issue.  If it comes up again, please let me know and I will re-open it.

**Closed by sangwinc** 2020-04-03 13:30 UTC
