### ISSUE TITLE
"plot" throws error

### ISSUE THREAD

**Issue by ianjones** [maths/moodle-qtype_stack#409] opened 2018-10-12 10:33 UTC
{@plot(x^2,[x,-1,1])@}

throws

CASText failed validation.  The CAS returned the following error(s):plot(x^2,[x,-1,1]) caused the following error: set_plot_option: unknown plot option: svg_file

Suggestions appreciated.

**Comment by aharjula** [comment] 2018-10-12 10:39
Maxima version could probably explain this as SVG plotting is only a couple of years old feature it may not exist on all available Maxima versions. STACK has plotted as SVG for a while now but I am not sure we tested all the possible supported Maxima versions for this if one of them does not support this then I guess it will need to be dropped from the supported list.

So which version of Maxima do you have?

**Comment by ianjones** [comment] 2018-10-12 12:44
Thank you, and sorry I'm so ill-informed on these matters. Our tech is currently on jury service so I will ask him when he gets back.

**Comment by sangwinc** [comment] 2018-10-12 13:19
That is most likely to be the reason....

**Comment by aharjula** [comment] 2018-10-14 16:12
Chris, the [new Maxima census](https://raw.githubusercontent.com/aharjula/moodle-qtype_stack/3351294d9c610188f386ca96961261518d4c9fe8/stack/cas/base-identifier-map.json) of that parser project tells us that `svg_file` has only been in the docs from 5.32.0 so should we drop earlier versions? There are quite a lot of them... alternatively we need to guide people on how to toggle the other plot output logic if it still exists.

**Comment by sangwinc** [comment] 2018-10-14 17:49
Well, it looks like 5.32.0 was released before 2013-12-25 (https://sourceforge.net/projects/maxima/files/Maxima-Linux/)  I'd be happy to draw a line under it as far as official releases go.   Indeed, we already have!  See https://github.com/maths/moodle-qtype_stack/blob/master/doc/en/Installation/index.md  

Ian, if Loughborough really can't upgrade Maxima, then I'll sort something out privately to get you sorted out....
Can you confirm what Maxima version you are running?

**Comment by sangwinc** [comment] 2018-11-01 17:57
Ian,
I'm confident this issue is a local setup problem, not a bug in STACK so I've decided to close this issue. If you disagree please re-open it.  Happy to correspond by email and get this fixed for you locally.
Chris

**Closed by sangwinc** 2018-11-01 17:57 UTC
